# https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 55
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

# https://home-assistant.io/components/http/
http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  base_url: !secret http_url
  server_port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# https://home-assistant.io/components/updater/
updater:
  include_used_components: true

# https://home-assistant.io/components/config/
config:

# https://home-assistant.io/components/frontend/
frontend:

# https://www.home-assistant.io/components/recorder/
recorder:
  purge_keep_days: 2

# https://home-assistant.io/components/history/
history:

# https://home-assistant.io/components/map/
map:

# https://home-assistant.io/hassio/
hassio:

# https://home-assistant.io/components/device_tracker/
device_tracker:
  # https://home-assistant.io/components/device_tracker.fritz/
  - platform: fritz
    host: 192.168.5.1
    username: !secret fritz_username
    password: !secret fritz_password
    track_new_devices: false

# https://home-assistant.io/components/sensor/
sensor:

  # https://home-assistant.io/components/sensor.systemmonitor/
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m

  # https://home-assistant.io/components/sensor.moon/
  - platform: moon

  # https://home-assistant.io/components/sensor.yr/
  - platform: yr

  # https://home-assistant.io/components/sensor.miflora/
  - platform: miflora
    mac: "C4:7C:8D:65:AF:DD"
    name: Helix
  #- platform: miflora
  #  mac: "C4:7C:8D:65:B0:5A"
  #  name: Helix
  #  timeout: 12

# https://www.home-assistant.io/components/plant/
plant:
  helix:
    name: Helix
    sensors:
      moisture: sensor.helix_moisture
      conductivity: sensor.helix_conductivity
      brightness: sensor.helix_light_intensity
      temperature: sensor.helix_temperature
      battery: sensor.helix_battery
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 1200
    max_brightness: 40000
    min_temperature: 10
    max_temperature: 32
    min_battery: 10

# https://home-assistant.io/components/tradfri/
tradfri:
  host: 192.168.5.57
  allow_tradfri_groups: false

# https://home-assistant.io/components/light/
light:
  # https://home-assistant.io/components/light.limitlessled/
  - platform: limitlessled
    bridges:
      - host: 192.168.5.56
        version: 2
        port: 8899
        groups:
          - number: 1
            name: Shelf
          - number: 2
            name: TV

  # https://www.home-assistant.io/components/light.group/
  - platform: group
    name: Livingroom Ceiling Lights
    entities:
      - light.livingroom_ceiling_bulb_1
      - light.livingroom_ceiling_bulb_2
      - light.livingroom_ceiling_bulb_3
      - light.livingroom_ceiling_bulb_4
  - platform: group
    name: Livingroom Accent Lights
    entities:
      - light.shelf
      - light.tv

# https://home-assistant.io/components/switch/
switch:
  # https://home-assistant.io/components/switch.template/
  - platform: template
    switches:
      blink:
        friendly_name: "Blink"
        value_template: "{{ is_state('binary_sensor.blink_armed_status', 'on') }}"
        turn_on:
          service: blink.arm_system
          data:
            device_armed: true
        turn_off:
          service: blink.arm_system
          data:
            device_armed: false

  # https://home-assistant.io/components/switch.wake_on_lan/
  - platform: wake_on_lan
    name: Byss
    mac_address: "C8:60:00:84:F9:02"
    host: 192.168.5.5
    turn_off:
      service: shell_command.turn_off_byss

shell_command:
  turn_off_byss: 'ssh -i /config/hassio_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null hassio@192.168.5.5 date'

# https://home-assistant.io/components/apple_tv/
apple_tv:
  - host: 192.168.5.51
    login_id: !secret appletv_token
    start_off: true

# https://home-assistant.io/components/media_player/
media_player:
  # https://home-assistant.io/components/media_player.plex/
  - platform: plex

  # https://home-assistant.io/components/media_player.spotify/
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

# https://home-assistant.io/components/hdmi_cec/
hdmi_cec:

# https://home-assistant.io/components/blink/
blink:
  username: !secret blink_username
  password: !secret blink_password

# https://home-assistant.io/components/weather/
weather:
  # https://home-assistant.io/components/weather.yweather/
  - platform: yweather
    woeid: 657169

# https://home-assistant.io/components/sun/
sun:

# https://home-assistant.io/components/tts/
tts:
  # https://home-assistant.io/components/tts.google/
  - platform: google

# https://home-assistant.io/components/notify/
notify:
  # https://home-assistant.io/components/notify.pushover/
  - platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

# https://home-assistant.io/components/alexa/
alexa:
  flash_briefings:
    whoishome:
      - title: Who's at home?
        text: >
          You are home, you silly

intent_script:
  amzn1.ask.skill.c86aacc5-2381-40b5-8151-460ddbc1b19e:
    action:
      service: script.1508878187697
    speech:
      type: plain
      text: OK

# https://home-assistant.io/components/emulated_hue/
emulated_hue:
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - script

# https://www.home-assistant.io/components/homekit/
homekit:

# https://home-assistant.io/docs/ecosystem/ios/
ios:

# https://home-assistant.io/components/zeroconf/
zeroconf:

# https://home-assistant.io/components/prometheus/
#prometheus:

# https://github.com/pkozul/ha-floorplan
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# https://home-assistant.io/components/logger/
logger:
  default: warning
  #logs:
  #  homeassistant.components.sensor.miflora: debug

group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
automation: !include automations.yaml
