# https://www.home-assistant.io/docs/automation/

##
## Wall Switchs
##

- id: '1621193284025'
  alias: 'Bedroom Wall Switch Channel 1'
  description: ''
  mode: single
  trigger:
  - platform: event
    event_type: shelly.click
    event_data:
      device: shellyswitch25-483FDA4CE546
      channel: 1
  action:
  - variables:
      # single, double, triple, long, single_long, long_single
      event: '{{ trigger.event.data.click_type }}'
  - choose:
    - conditions:
      - '{{ event == "single" }}'
      sequence:
      - service: light.toggle
        entity_id: light.tradfri_bulb_e27_opal_1000lm_744e24fe
    - conditions:
      - '{{ event == "long" }}'
      sequence:
      - service: switch.toggle
        entity_id: switch.shellyswitch25_483FDA4CE546_channel_1

- id: '1621193284027'
  alias: 'Living Room Wall Switch Channel 1'
  description: ''
  mode: single
  trigger:
  - platform: event
    event_type: shelly.click
    event_data:
      device: shellyswitch25-40F520015F98
      channel: 1
  action:
  - variables:
      # single, double, triple, long, single_long, long_single
      event: '{{ trigger.event.data.click_type }}'
  - choose:
    - conditions:
      - '{{ event == "single" }}'
      sequence:
      - service: switch.turn_on
        entity_id: switch.shellyswitch25_40f520015f98_channel_1
      - service: light.toggle
        entity_id: light.zha_group_0x0002
    - conditions:
      - '{{ event == "long" }}'
      sequence:
      - service: switch.toggle
        entity_id: switch.shellyswitch25_40f520015f98_channel_1

- id: '1621193284028'
  alias: 'Living Room Wall Switch Channel 2'
  description: ''
  mode: single
  trigger:
  - platform: event
    event_type: shelly.click
    event_data:
      device: shellyswitch25-40F520015F98
      channel: 2
  action:
  - variables:
      # single, double, triple, long, single_long, long_single
      event: '{{ trigger.event.data.click_type }}'
  - choose:
    - conditions:
      - '{{ event == "single" }}'
      sequence:
      - service: light.toggle
        entity_id: light.livingroom_accent_lights
    - conditions:
      - '{{ event == "double" }}'
      sequence:
      - service: light.toggle
        entity_id: light.livingroom_floor_lamp

##
## Wake-me up using bedroom lights
## https://www.wouterbulten.nl/blog/tech/custom-wake-up-light-with-home-assistant/
##

- id: '1621193285000'
  alias: 'Wake-me up using bedroom lights'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.wakeup_weekend
          state: 'on'
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
  action:
    - service: light.turn_on
      entity_id: light.ikea_tradfri_bulb_e27_opal_1000lm_1
      data:
        transition: 1800  # seconds => 30min
        brightness: 255

##
## Theme Day/Night Switch
##

- id: '1621193286000'
  alias: 'Set theme for day and night'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
            clear
          {% else %}
            clear-dark
          {% endif %}

