# https://www.home-assistant.io/docs/automation/

# Wake-me up using bedroom lights
# https://www.wouterbulten.nl/blog/tech/custom-wake-up-light-with-home-assistant/
- alias: 'Wake-me up using bedroom lights'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.wakeup_weekend
          state: 'on'
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
  action:
    - service: light.turn_on
      entity_id: light.ikea_tradfri_bulb_e27_opal_1000lm_1
      data:
        transition: 1800  # seconds => 30min
        brightness: 255

- alias: 'Set theme for day and night'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
            clear
          {% else %}
            dark
          {% endif %}
