# https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 55
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

# https://home-assistant.io/components/http/
http:
  base_url: !secret http_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

# https://home-assistant.io/components/updater/
updater:
  include_used_components: true

# https://home-assistant.io/components/config/
config:

# https://home-assistant.io/components/frontend/
frontend:

# https://www.home-assistant.io/components/recorder/
recorder:

# https://home-assistant.io/components/history/
history:

# https://www.home-assistant.io/components/logbook/
# logbook:

# https://home-assistant.io/components/map/
map:

# https://www.home-assistant.io/components/discovery/
discovery:
  ignore:
    - apple_tv
    - axis
    - belkin_wemo
    - bluesound
    - bose_soundtouch
    - denonavr
    - directv
    - frontier_silicon
    - google_cast
    - harmony
    - ikea_tradfri
    - logitech_mediaserver
    - netgear_router
    - openhome
    - panasonic_viera
    - philips_hue
    #- plex_mediaserver
    - roku
    - sabnzbd
    - samsung_printer
    - samsung_tv
    - sonos
    - songpal
    - tellstick
    - wink
    - yamaha
    - yeelight
    - xiaomi_gw
#  enable:
#    # https://www.home-assistant.io/components/homekit_controller/
#    - homekit

# https://home-assistant.io/components/device_tracker/
device_tracker:
  # https://home-assistant.io/components/device_tracker.fritz/
  - platform: fritz
    host: 192.168.5.1
    username: !secret fritz_username
    password: !secret fritz_password
    new_device_defaults:
      track_new_devices: false

# https://home-assistant.io/components/sensor/
sensor:
  - platform: airco2ntrol

  # https://home-assistant.io/components/sensor.miflora/
  - platform: miflora
    mac: "C4:7C:8D:65:B0:5A"
    name: Poinsettia
  #- platform: miflora
  #  mac: "C4:7C:8D:65:AF:DD"
  #  name: Helix
  #  timeout: 12

  # https://home-assistant.io/components/sensor.systemmonitor/
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m

  # https://home-assistant.io/components/sensor.moon/
  - platform: moon

  # https://home-assistant.io/components/sensor.yr/
  - platform: yr

# https://www.home-assistant.io/components/binary_sensor.trend/
binary_sensor:
  # https://www.home-assistant.io/components/binary_sensor.iss/
  - platform: iss

# https://home-assistant.io/components/tradfri/
tradfri:
  host: 192.168.5.57
  allow_tradfri_groups: false

# https://home-assistant.io/components/light/
light:
  # https://home-assistant.io/components/light.limitlessled/
  - platform: limitlessled
    bridges:
      - host: 192.168.5.56
        version: 2
        port: 8899
        groups:
          - number: 1
            name: Shelf
          - number: 2
            name: TV

  # https://www.home-assistant.io/components/light.group/
  - platform: group
    name: Livingroom Ceiling Lights
    entities:
      - light.livingroom_ceiling_bulb_1
      - light.livingroom_ceiling_bulb_2
      - light.livingroom_ceiling_bulb_3
      - light.livingroom_ceiling_bulb_4
  - platform: group
    name: Livingroom Accent Lights
    entities:
      - light.shelf
      - light.tv

# https://home-assistant.io/components/switch/
switch:
  # https://home-assistant.io/components/switch.template/
  - platform: template
    switches:
      blink:
        friendly_name: "Blink"
        value_template: "{{ is_state('binary_sensor.blink_armed_status', 'on') }}"
        turn_on:
          service: blink.arm_system
          data:
            device_armed: true
        turn_off:
          service: blink.arm_system
          data:
            device_armed: false

  # https://home-assistant.io/components/switch.wake_on_lan/
  - platform: wake_on_lan
    name: Byss
    mac_address: "C8:60:00:84:F9:02"
    host: 192.168.5.5
    turn_off:
      service: shell_command.turn_off_byss

# https://home-assistant.io/components/apple_tv/
apple_tv:
  - host: 192.168.5.51
    login_id: !secret appletv_token
    start_off: true

# https://home-assistant.io/components/media_player/
media_player:
  # https://home-assistant.io/components/media_player.plex/
  - platform: plex

  # https://home-assistant.io/components/media_player.spotify/
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

# https://home-assistant.io/components/hdmi_cec/
# hdmi_cec:

# https://home-assistant.io/components/weather/
weather:
  # https://home-assistant.io/components/weather.yweather/
  - platform: yweather
    woeid: 657169

# https://home-assistant.io/components/sun/
sun:

# https://www.home-assistant.io/components/plant/
plant:
  Helix:
    sensors:
      moisture: sensor.poinsettia_moisture
      conductivity: sensor.poinsettia_conductivity
      brightness: sensor.poinsettia_light_intensity
      temperature: sensor.poinsettia_temperature
      battery: sensor.poinsettia_battery
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 4000
    max_brightness: 30000
    min_temperature: 8
    max_temperature: 35
    min_battery: 10

# https://home-assistant.io/components/blink/
blink:
  username: !secret blink_username
  password: !secret blink_password

# https://home-assistant.io/components/notify/
notify:
  # https://home-assistant.io/components/notify.pushover/
  - platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

# https://www.home-assistant.io/components/homekit/
homekit:
  filter:
    include_entities:
      - light.shelf
      - light.tv
      - sensor.airco2ntrol_carbon_dioxide
      - sensor.airco2ntrol_temperature

# https://home-assistant.io/components/logger/
logger:
  # default: warning
  default: info
  logs:
    custom_components.sensor.airco2ntrol: debug
    homeassistant.components.sensor.miflora: debug

group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
automation: !include automations.yaml
