# https://www.home-assistant.io/docs/configuration/basic
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 55
  unit_system: metric
  time_zone: Europe/Berlin
  external_url: !secret url
  internal_url: !secret url
  allowlist_external_dirs:
    - /config
  customize: !include customize.yaml

# https://www.home-assistant.io/integrations/http
http:
  server_port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

# https://www.home-assistant.io/integrations/default_config
default_config:

# https://www.home-assistant.io/integrations/frontend
frontend:
  themes: !include_dir_merge_named themes

# https://www.home-assistant.io/lovelace
lovelace:
  mode: yaml
  resources:
    # https://github.com/thomasloven/lovelace-layout-card
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    # https://github.com/maxwroc/battery-state-card
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    # https://github.com/ExperienceLovelace/ha-floorplan
    - url: /hacsfiles/ha-floorplan/floorplan.js
      type: module
    # https://github.com/kalkih/mini-graph-card
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    # https://github.com/nervetattoo/simple-thermostat
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    # https://github.com/jansauer/lovelace-flower-card
    # - url: "http://127.0.0.1:5000/flower-card.js"
    - url: /hacsfiles/lovelace-flower-card/flower-card.js
      type: module
#     # https://github.com/thomasloven/lovelace-card-mod
#     - url: /hacsfiles/lovelace-card-mod/card-mod.js
#       type: module
  dashboards:
    lovelace-insides:
      mode: yaml
      title: Insides
      icon: mdi:stethoscope
      filename: ui-insides.yaml

# https://www.home-assistant.io/integrations/recorder
recorder:

# https://www.home-assistant.io/integrations/ios
# https://companion.home-assistant.io
ios:

# https://www.home-assistant.io/integrations/person
person:
  - name: Jan Sauer
    id: jansauer
    user_id: e4a346c4e7c74089b57e0e664a87c166
    device_trackers:
      - device_tracker.iphone_x

# https://www.home-assistant.io/integrations/zha
zha:
  database_path: /config/zigbee.db
  zigpy_config:
    ota:
      ikea_provider: true

# https://github.com/StyraHem/ShellyForHASS
shelly:
  discovery: false
  username: !secret shelly_username
  password: !secret shelly_password
  devices:
    - id: "40F520015F98" # Living Room
    - id: "483FDA4CE546" # Bedroom
  sensors:
    - switch
    - current_consumption

# https://www.home-assistant.io/integrations/sensor
sensor:
  - platform: airco2ntrol

  # https://www.home-assistant.io/integrations/miflora
  - platform: miflora
    name: Ficus
    mac: "C4:7C:8D:65:AF:DD"
  - platform: miflora
    name: Sansevieria Cylindrica Boncel
    mac: "C4:7C:8D:6B:A3:89"
  - platform: miflora
    name: Callisia Repens
    mac: "C4:7C:8D:6B:A3:80"
  - platform: miflora
    name: Basil
    mac: "C4:7C:8D:6B:A3:26"
  - platform: miflora
    name: Pteris
    mac: "C4:7C:8D:65:B0:5A"

  # https://www.home-assistant.io/integrations/systemmonitor
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m

  # https://www.home-assistant.io/integrations/uptime
  - platform: uptime

  # https://www.home-assistant.io/integrations/filesize
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db

  # https://www.home-assistant.io/integrations/moon
  - platform: moon

  # https://www.home-assistant.io/integrations/dwd_weather_warnings
  - platform: dwd_weather_warnings
    region_name: 803241001

  # https://www.home-assistant.io/integrations/time_date
  - platform: time_date
    display_options:
      - 'time'

# https://www.home-assistant.io/integrations/input_datetime
input_datetime:
  wakeup_time:
    name: "Start lights at"
    has_time: true
    has_date: false
    initial: "06:30"

# https://www.home-assistant.io/integrations/binary_sensor
binary_sensor:
  # https://www.home-assistant.io/integrations/iss
  - platform: iss

# https://www.home-assistant.io/integrations/input_boolean
input_boolean:
  wakeup_weekend:
    name: "Enable Wake-up on weekends"
    icon: mdi:calendar-blank
    initial: off
  mode_guest_mode:
    name: Guest Mode
    icon: mdi:drama-masks
    initial: off
#   mode_do_not_disturb:
#     name: Do Not Disturb
#     icon: mdi:bell-off
#     initial: off
#   mode_vacation_mode:
#     name: Vacation Mode
#     icon: mdi:beach
#     initial: off

# https://www.home-assistant.io/integrations/light
light:
  # https://www.home-assistant.io/integrations/limitlessled
  - platform: limitlessled
    bridges:
      - host: 192.168.5.56
        version: 2
        port: 8899
        groups:
          - number: 1
            name: Shelf
          - number: 2
            name: TV

  # https://www.home-assistant.io/integrations/light.switch
  - platform: switch
    name: Livingroom Floor Lamp
    entity_id: switch.osram_plug_1

  # https://www.home-assistant.io/integrations/light.group
  - platform: group
    name: Livingroom Ceiling Lights
    entities:
      - light.ikea_tradfri_bulb_gu10_ws_400lm_1
      - light.ikea_tradfri_bulb_gu10_ws_400lm_2
      - light.ikea_tradfri_bulb_gu10_ws_400lm_4
      - light.ikea_tradfri_bulb_gu10_ws_400lm_3
  - platform: group
    name: Livingroom Accent Lights
    entities:
      - light.shelf
      - light.tv

# https://www.home-assistant.io/integrations/switch
switch:
  # https://www.home-assistant.io/integrations/wake_on_lan
  - platform: wake_on_lan
    name: Byss
    mac: "C8:60:00:84:F9:02"
    host: 192.168.5.5
    turn_off:
      service: shell_command.turn_off_byss

# https://www.home-assistant.io/integrations/shell_command
shell_command:
  turn_off_byss: 'ssh -i /config/byss-hassio_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null hassio@192.168.5.5 date'

# https://www.home-assistant.io/integrations/spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# https://www.home-assistant.io/integrations/hdmi_cec
# hdmi_cec:
#   devices:
#     TV: 0.0.0.0
#     AV Receiver: 1.0.0.0
#     Apple TV: 1.1.0.0
#     Home Assistant: 1.2.0.0
#   platform: switch
  # types:
  #   hdmi_cec.TV: media_player

# https://www.home-assistant.io/integrations/sun
sun:

# https://www.home-assistant.io/integrations/weather
weather:
  # https://www.home-assistant.io/integrations/weather.darksky
  # https://darksky.net/dev/docs#response-format
  - platform: darksky
    api_key: !secret darksky_api_key 

# https://www.home-assistant.io/integrations/plant
plant:
  Sansevieria Cylindrica Boncel:
    sensors:
      moisture: sensor.sansevieria_cylindrica_boncel_moisture
      conductivity: sensor.sansevieria_cylindrica_boncel_conductivity
      brightness: sensor.sansevieria_cylindrica_boncel_light_intensity
      temperature: sensor.sansevieria_cylindrica_boncel_temperature
      battery: sensor.sansevieria_cylindrica_boncel_battery
    min_moisture: 7
    max_moisture: 50
    min_conductivity: 300
    max_conductivity: 1000
    min_brightness: 1500
    max_brightness: 60000
    min_temperature: 10
    max_temperature: 32
    min_battery: 10
  Callisia Repens:
    sensors:
      moisture: sensor.callisia_repens_moisture
      conductivity: sensor.callisia_repens_conductivity
      brightness: sensor.callisia_repens_light_intensity
      temperature: sensor.callisia_repens_temperature
      battery: sensor.callisia_repens_battery
    min_moisture: 20
    max_moisture: 65
    min_conductivity: 50
    max_conductivity: 2000
    min_brightness: 500
    max_brightness: 40000
    min_temperature: 12
    max_temperature: 35
    min_battery: 10
  Ficus:
    sensors:
      moisture: sensor.ficus_moisture
      conductivity: sensor.ficus_conductivity
      brightness: sensor.ficus_light_intensity
      temperature: sensor.ficus_temperature
      battery: sensor.ficus_battery
    min_moisture: 15
    max_moisture: 65
    min_conductivity: 350
    max_conductivity: 2000
    # min_brightness: 1000
    max_brightness: 22500
    min_temperature: 15
    max_temperature: 32
    min_battery: 10
  Pteris:
    sensors:
      moisture: sensor.pteris_moisture
      conductivity: sensor.pteris_conductivity
      brightness: sensor.pteris_light_intensity
      temperature: sensor.pteris_temperature
      battery: sensor.pteris_battery
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 1500
    min_brightness: 500
    max_brightness: 15000
    min_temperature: 10
    max_temperature: 32
    min_battery: 10
  Basil:
    sensors:
      moisture: sensor.basil_moisture
      conductivity: sensor.basil_conductivity
      brightness: sensor.basil_light_intensity
      temperature: sensor.basil_temperature
      battery: sensor.basil_battery
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 2500
    max_brightness: 60000
    min_temperature: 8
    max_temperature: 32
    min_battery: 10

# https://www.home-assistant.io/integrations/netatmo
netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

# https://www.home-assistant.io/integrations/withings
withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_client_secret

# https://www.home-assistant.io/integrations/homekit
homekit:
  filter:
    include_entities:
      # Entryway
      # Livingroom
      - light.livingroom_ceiling_lights
      - switch.osram_plug_1
      - light.shelf
      - light.tv
      - sensor.airco2ntrol_carbon_dioxide
      - sensor.airco2ntrol_temperature
      - scene.livingroom_night_light
      # Bedroom
      - light.ikea_tradfri_bulb_e27_opal_1000lm_1
      # - sensor.sleepy_temperature
      # - sensor.sleepy_humidity

# https://www.home-assistant.io/integrations/emulated_hue
emulated_hue:
  host_ip: 192.168.5.2
  listen_port: 80
  expose_by_default: false
  entities:
    light.livingroom_ceiling_lights:
      name: Ceiling Lights
      hidden: false
    switch.osram_plug_1:
      name: Floor Lamp
      hidden: false
    light.tv:
      hidden: false
    light.shelf:
      hidden: false

# https://www.home-assistant.io/integrations/notify
# https://companion.home-assistant.io/docs/notifications/notifications-basic
notify:
  # https://www.home-assistant.io/integrations/pushover
  - platform: pushover
    name: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

# https://www.home-assistant.io/integrations/influxdb
influxdb:
  host: a0d7b954-influxdb
  # host: 192.168.5.2
  port: 8086
  database: homeassistant
  username: homeassistant
  password: rqJg9AaWGDbQuGA
  max_retries: 3
  include:
    domains:
      - climate
      - plant
    entity_globs:
      - sensor.withings_*
    entities:
      - sensor.airco2ntrol_temperature
      - sensor.airco2ntrol_carbon_dioxide
      - sensor.windy_temperature
      - sensor.windy_humidity
      - sensor.windy_pm_2_5
      - sensor.windy_pm_10_0

# https://www.home-assistant.io/integrations/logger
logger:
  default: warning
  # default: debug
  # logs:
    # homeassistant.components.alexa: debug
    # homeassistant.components.miflora: debug
    # custom_components.airco2ntrol: debug

zone: !include zones.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
automation: !include automations.yaml
