# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 55
  unit_system: metric
  time_zone: Europe/Berlin
  whitelist_external_dirs:
    - /config
  customize: !include customize.yaml

# https://www.home-assistant.io/components/http/
http:
  base_url: !secret http_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

# https://www.home-assistant.io/components/updater/
updater:
  include_used_components: true

# https://www.home-assistant.io/components/config/
config:

# https://www.home-assistant.io/components/frontend/
frontend:
  themes: !include themes.yaml

# https://www.home-assistant.io/lovelace/
lovelace:
  mode: yaml

# https://www.home-assistant.io/components/recorder/
recorder:

# https://www.home-assistant.io/components/history/
history:

# https://www.home-assistant.io/components/logbook/
# logbook:

# https://www.home-assistant.io/components/map/
map:

# https://www.home-assistant.io/components/system_health/
system_health:

# https://www.home-assistant.io/integrations/discovery/
discovery:
  ignore:
    - plex_mediaserver

# https://www.home-assistant.io/integrations/mobile_app/
mobile_app:

# https://www.home-assistant.io/components/ios/
ios:

# https://www.home-assistant.io/components/person/
person:
  - name: Jan Sauer
    id: jansauer
    user_id: e4a346c4e7c74089b57e0e664a87c166
    device_trackers:
      - device_tracker.iphone_x

# https://www.home-assistant.io/components/device_tracker/
device_tracker:
  # https://www.home-assistant.io/components/device_tracker.fritz/
  - platform: fritz
    host: 192.168.5.1
    username: !secret fritz_username
    password: !secret fritz_password
    new_device_defaults:
      track_new_devices: false

# https://www.home-assistant.io/components/zha/
zha:
  usb_path: /dev/ttyUSB0
  database_path: /config/zigbee.db

# https://www.home-assistant.io/components/xiaomi_aqara/
xiaomi_aqara:
  gateways:
    - mac: 78:11:DC:FA:EA:5B
      key: !secret xiaomi_gateway_kex

# https://www.home-assistant.io/components/sensor/
sensor:
  - platform: airco2ntrol

  # https://www.home-assistant.io/components/sensor.miflora/
  - platform: miflora
    name: Snowflower
    mac: "C4:7C:8D:65:AF:DD"
  - platform: miflora
    name: Balcony
    mac: "C4:7C:8D:65:B0:5A"

  # https://www.home-assistant.io/components/sensor.systemmonitor/
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m

  # https://www.home-assistant.io/components/uptime/
  - platform: uptime

  # https://www.home-assistant.io/components/filesize/
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db

  # https://www.home-assistant.io/components/sensor.moon/
  - platform: moon

  # https://www.home-assistant.io/components/sensor.yr/
  - platform: yr

  # https://www.home-assistant.io/components/time_date/
  - platform: time_date
    display_options:
      - 'time'

# https://www.home-assistant.io/components/input_datetime/
input_datetime:
  wakeup_time:
    name: "Start lights at"
    has_time: true
    has_date: false
    initial: "06:30"

# https://www.home-assistant.io/components/timer/
timer:
  entryway:
    duration: '00:00:10'

# https://www.home-assistant.io/components/binary_sensor.trend/
binary_sensor:
  # https://www.home-assistant.io/components/binary_sensor.iss/
  - platform: iss

# https://www.home-assistant.io/components/input_boolean/
input_boolean:
  wakeup_weekend:
    name: "Enable Wake-up on weekends"
    icon: mdi:calendar-blank
    initial: off
  mode_guest_mode:
    name: Guest Mode
    icon: mdi:drama-masks
    initial: off
#   mode_do_not_disturb:
#     name: Do Not Disturb
#     icon: mdi:bell-off
#     initial: off
#   mode_vacation_mode:
#     name: Vacation Mode
#     icon: mdi:beach
#     initial: off

# https://www.home-assistant.io/components/light/
light:
  # https://www.home-assistant.io/components/light.limitlessled/
  - platform: limitlessled
    bridges:
      - host: 192.168.5.56
        version: 2
        port: 8899
        groups:
          - number: 1
            name: Shelf
          - number: 2
            name: TV

  # https://www.home-assistant.io/integrations/light.group/
  - platform: group
    name: Livingroom Ceiling Lights
    entities:
      - light.ikea_tradfri_bulb_gu10_ws_400lm_1
      - light.ikea_tradfri_bulb_gu10_ws_400lm_2
      - light.ikea_tradfri_bulb_gu10_ws_400lm_4
      - light.ikea_tradfri_bulb_gu10_ws_400lm_3
  - platform: group
    name: Livingroom Accent Lights
    entities:
      - light.shelf
      - light.tv

# https://www.home-assistant.io/components/switch/
switch:
  # https://www.home-assistant.io/components/switch.wake_on_lan/
  - platform: wake_on_lan
    name: Byss
    mac: "C8:60:00:84:F9:02"
    host: 192.168.5.5
    turn_off:
      service: shell_command.turn_off_byss

# https://www.home-assistant.io/integrations/shell_command/
shell_command:
  turn_off_byss: 'ssh -i /config/byss-hassio_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null hassio@192.168.5.5 date'

# https://www.home-assistant.io/components/apple_tv/
apple_tv:
  - host: 192.168.5.58
    name: Living Room
    login_id: !secret appletv_loginid
    credentials: !secret appletv_credentials
    start_off: true

# https://www.home-assistant.io/components/media_player/
media_player:
  # https://www.home-assistant.io/components/media_player.spotify/
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

# https://www.home-assistant.io/components/hdmi_cec/
# hdmi_cec:

# https://www.home-assistant.io/components/sun/
sun:

# https://www.home-assistant.io/components/weather/
weather:
  # https://www.home-assistant.io/components/weather.darksky/
  # https://darksky.net/dev/docs#response-format
  - platform: darksky
    api_key: !secret darksky_api_key 

# https://www.home-assistant.io/components/plant/
plant:
  Snowflower:
    sensors:
      moisture: sensor.snowflower_moisture
      conductivity: sensor.snowflower_conductivity
      brightness: sensor.snowflower_light_intensity
      temperature: sensor.snowflower_temperature
      battery: sensor.snowflower_battery
    min_moisture: 15
    max_moisture: 65
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 15
    max_temperature: 32
    # min_brightness: 1000
    max_brightness: 22500
  Balcony:
    sensors:
      moisture: sensor.balcony_moisture
      conductivity: sensor.balcony_conductivity
      brightness: sensor.balcony_light_intensity
      temperature: sensor.balcony_temperature
      battery: sensor.balcony_battery
    min_moisture: 15
    max_moisture: 60
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 8
    max_temperature: 35
    min_brightness: 3000
    max_brightness: 35000

# https://www.home-assistant.io/integrations/netatmo/
netatmo:
  api_key: !secret netatmo_client_id
  secret_key: !secret netatmo_client_secret
  username: !secret netatmo_username
  password: !secret netatmo_password

# https://www.home-assistant.io/components/withings/
withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_client_secret

# https://github.com/custom-components/alexa_media_player
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.de

# https://www.home-assistant.io/components/homekit/
homekit:
  filter:
    include_entities:
      # Entryway
      - switch.wall_switch_158d000161469d
      # Livingroom
      # - light.ikea_tradfri_bulb_gu10_ws_400lm_1
      # - light.ikea_tradfri_bulb_gu10_ws_400lm_2
      # - light.ikea_tradfri_bulb_gu10_ws_400lm_4
      # - light.ikea_tradfri_bulb_gu10_ws_400lm_3
      - switch.osram_plug_1
      - light.shelf
      - light.tv
      - sensor.airco2ntrol_carbon_dioxide
      - sensor.airco2ntrol_temperature
      # Bedroom
      - light.ikea_tradfri_bulb_e27_opal_1000lm_1
      - light.gateway_light_7811dcfaea5b
      # - sensor.sleepy_temperature
      # - sensor.sleepy_humidity

# https://home-assistant.io/components/emulated_hue/
emulated_hue:
  host_ip: 192.168.5.2
  listen_port: 80
  expose_by_default: false
  entities:
    light.livingroom_ceiling_lights:
      name: Ceiling Lights
      hidden: false
    switch.osram_plug_1:
      name: Floor Lamp
      hidden: false
    light.tv:
      hidden: false
    light.shelf:
      hidden: false

# https://www.home-assistant.io/components/notify/
# https://www.home-assistant.io/components/#notifications
notify:
  # https://www.home-assistant.io/components/notify.pushover/
  - platform: pushover
    name: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  
  # https://github.com/custom-components/alexa_media_player/wiki/Notification-Component
  - platform: alexa_media
    name: alexa_media

# https://www.home-assistant.io/integrations/sentry/
sentry:
  dsn: !secret sentry_dsn

# https://www.home-assistant.io/components/logger/
logger:
  default: warning
  # default: debug
  logs:
    # custom_components.airco2ntrol: debug
    # homeassistant.components.sensor.miflora: debug
    homeassistant.components.sentry: debug

zone: !include zones.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
automation: !include automations.yaml
