# https://www.home-assistant.io/integrations/default_config
default_config:

# https://www.home-assistant.io/integrations/http
http:
  server_port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# https://www.home-assistant.io/integrations/sensor
sensor:
  # https://www.home-assistant.io/integrations/miflora
  - platform: miflora
    name: Ficus
    mac: "C4:7C:8D:65:AF:DD"
  - platform: miflora
    name: Poinsettia
    mac: "C4:7C:8D:6B:A3:80"

  # https://www.home-assistant.io/integrations/systemmonitor
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m

  # https://www.home-assistant.io/integrations/uptime
  - platform: uptime

  # https://www.home-assistant.io/integrations/dwd_weather_warnings
  - platform: dwd_weather_warnings
    region_name: 803241001

  # https://www.home-assistant.io/integrations/moon
  - platform: moon

  # https://www.home-assistant.io/integrations/time_date
  - platform: time_date
    display_options:
      - 'time'

  # https://www.home-assistant.io/integrations/sensor.rest
  # https://github.com/Arksine/moonraker/blob/master/docs/example-home-assistant.yaml
  - platform: rest
    name: Sidewinder X1
    resource: "http://192.168.5.64:7125/printer/objects/query?heater_bed&extruder&print_stats&toolhead&display_status&virtual_sdcard"
    json_attributes_path: "$.result.status"
    json_attributes:
      - heater_bed
      - extruder
      - print_stats
      - toolhead
      - display_status
      - virtual_sdcard
    value_template: >-
      {{ 'OK' if ('result' in value_json) else None }}

  # https://www.home-assistant.io/integrations/template
  - platform: template
    sensors:
      sidewinder_x1_state:
        friendly_name: 'Sidewinder X1 State'
        icon_template: mdi:printer-3d
        value_template: >-
          {{ states.sensor.sidewinder_x1.attributes['print_stats']['state'] if is_state('sensor.sidewinder_x1', 'OK') else None }}
      sidewinder_x1_current_print:
        friendly_name: 'Sidewinder X1 Current Print'
        value_template: >-
          {{ states.sensor.sidewinder_x1.attributes['print_stats']['filename'] if is_state('sensor.sidewinder_x1', 'OK') else None }}
      sidewinder_x1_current_progress:
        friendly_name: 'Sidewinder X1 Print Progress'
        unit_of_measurement: '%'
        icon_template: mdi:file-percent
        value_template: >-
          {{ (states.sensor.sidewinder_x1.attributes['display_status']['progress'] * 100) | round(1) if is_state('sensor.sidewinder_x1', 'OK') else None }}
      sidewinder_x1_time_elapsed:
        friendly_name: 'Sidewinder X1 Print Time Elapsed'
        icon_template: mdi:clock-start
        value_template: >-
          {{ states.sensor.sidewinder_x1.attributes['print_stats']['print_duration'] | timestamp_custom("%H:%M:%S", 0) if is_state('sensor.sidewinder_x1', 'OK') else None }}
      sidewinder_x1_time_remaining:
        friendly_name: 'Sidewinder X1 Print Time Remaining'
        icon_template: mdi:clock-end
        value_template: >-
          {{ (((states.sensor.sidewinder_x1.attributes['print_stats']['print_duration'] / states.sensor.sidewinder_x1.attributes['display_status']['progress'] - states.sensor.voron_v0_sensor.attributes['print_stats']['print_duration']) if states.sensor.voron_v0_sensor.attributes['display_status']['progress'] > 0 else 0) | timestamp_custom('%H:%M:%S', 0)) if is_state('sensor.sidewinder_x1', 'OK') else None }}
      sidewinder_x1_eta:
        friendly_name: 'Sidewinder X1 Print ETA'
        icon_template: mdi:clock-outline
        value_template: >-
          {{ (as_timestamp(now()) + 2 * 60 * 60 + ((states.sensor.sidewinder_x1.attributes['print_stats']['print_duration'] / states.sensor.voron_v0_sensor.attributes['display_status']['progress'] - states.sensor.voron_v0_sensor.attributes['print_stats']['print_duration']) if states.sensor.sidewinder_x1.attributes['display_status']['progress'] > 0 else 0)) | timestamp_custom("%H:%M:%S", 0) if is_state('sensor.sidewinder_x1', 'OK') else None }}
      sidewinder_x1_hotend_target:
        friendly_name: 'Sidewinder X1 Hotend Target Temperature'
        device_class: temperature
        unit_of_measurement: '째C'
        value_template: >-
          {{ states.sensor.sidewinder_x1.attributes['extruder']['target'] | float | round(1) if is_state('sensor.sidewinder_x1', 'OK') else None }}
      sidewinder_x1_hotend_actual:
        friendly_name: 'Sidewinder X1 Hotend Actual Temperature'
        device_class: temperature
        unit_of_measurement: '째C'
        value_template: >-
          {{ states.sensor.sidewinder_x1.attributes['extruder']['temperature'] | float | round(1) if is_state('sensor.sidewinder_x1', 'OK') else None }}
      sidewinder_x1_bed_target:
        friendly_name: 'Sidewinder X1 Bed Target Temperature'
        device_class: temperature
        unit_of_measurement: '째C'
        value_template: >-
          {{ states.sensor.sidewinder_x1.attributes['heater_bed']['target'] | float | round(1) if is_state('sensor.sidewinder_x1', 'OK') else None }}
      sidewinder_x1_bed_actual:
        friendly_name: 'Sidewinder X1 Bed Actual Temperature'
        device_class: temperature
        unit_of_measurement: '째C'
        value_template: >-
          {{ states.sensor.sidewinder_x1.attributes['heater_bed']['temperature'] | float | round(1) if is_state('sensor.sidewinder_x1', 'OK') else None }}

# https://www.home-assistant.io/integrations/binary_sensor
binary_sensor:
  # https://www.home-assistant.io/integrations/iss
  - platform: iss

# https://www.home-assistant.io/integrations/input_datetime
input_datetime:
  wakeup_time:
    name: "Start lights at"
    has_time: true
    has_date: false
    initial: "06:30"

# https://www.home-assistant.io/integrations/input_boolean
input_boolean:
  wakeup_weekend:
    name: "Enable Wake-up on weekends"
    icon: mdi:calendar-blank
    initial: off
  mode_guest_mode:
    name: Guest Mode
    icon: mdi:drama-masks
    initial: off
  mode_vacation_mode:
    name: Vacation Mode
    icon: mdi:beach
    initial: off

# https://www.home-assistant.io/integrations/light
light:
  # https://www.home-assistant.io/integrations/limitlessled
  - platform: limitlessled
    bridges:
      - host: 192.168.5.56
        version: 2
        port: 8899
        groups:
          - number: 1
            name: Shelf
          - number: 2
            name: TV

  # https://www.home-assistant.io/integrations/light.switch
  - platform: switch
    name: Livingroom Floor Lamp
    entity_id: switch.osram_plug_01_a748010a_on_off

  # https://www.home-assistant.io/integrations/light.group
  - platform: group
    name: Livingroom Ceiling Lights
    entities:
      - light.ikea_tradfri_bulb_e511bcfe_level_light_color_on_off
      - light.ikea_tradfri_bulb_b40dbcfe_level_light_color_on_off
      - light.ikea_tradfri_bulb_7ca9bbfe_level_light_color_on_off
      - light.ikea_tradfri_bulb_a9feb1fe_level_light_color_on_off
  - platform: group
    name: Livingroom Accent Lights
    entities:
      - light.shelf
      - light.tv

# https://www.home-assistant.io/integrations/switch
switch:
  # https://www.home-assistant.io/integrations/switch.rest/
  - platform: rest
    name: sidewinder_x1_power
    resource: "http://192.168.5.64:7125/machine/device_power/device?device=Power"
    body_on: '{"action": "on"}'
    body_off: '{"action": "off"}'
    headers:
      Content-Type: 'application/json'
    is_on_template: >-
      {{ 'result' in value_json and (value_json.result.values() | list | first == "on") }}

  # https://www.home-assistant.io/integrations/wake_on_lan
  - platform: wake_on_lan
    name: Byss
    mac: "C8:60:00:84:F9:02"
    host: 192.168.5.5
    turn_off:
      service: shell_command.turn_off_byss

# https://www.home-assistant.io/integrations/shell_command
shell_command:
  turn_off_byss: 'ssh -i /config/byss-hassio_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null hassio@192.168.5.5 date'

# https://www.home-assistant.io/integrations/camera
camera:
  # https://www.home-assistant.io/integrations/mjpeg
  - platform: mjpeg
    name: Sidewinder X1
    mjpeg_url: http://192.168.5.64/webcam/?action=stream
    still_image_url: http://192.168.5.64/webcam/?action=snapshot

# https://www.home-assistant.io/integrations/plant
plant:
  Ficus:
    sensors:
      moisture: sensor.ficus_moisture
      conductivity: sensor.ficus_conductivity
      brightness: sensor.ficus_light_intensity
      temperature: sensor.ficus_temperature
      battery: sensor.ficus_battery
    min_moisture: 15
    max_moisture: 65
    min_conductivity: 350
    max_conductivity: 2000
    # min_brightness: 1000
    max_brightness: 22500
    min_temperature: 15
    max_temperature: 32
    min_battery: 10
  Poinsettia:
    sensors:
      moisture: sensor.poinsettia_moisture
      conductivity: sensor.poinsettia_conductivity
      brightness: sensor.poinsettia_light_intensity
      temperature: sensor.poinsettia_temperature
      battery: sensor.poinsettia_battery
    min_moisture: 15
    max_moisture: 65
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 4000
    max_brightness: 30000
    min_temperature: 8
    max_temperature: 35
    min_battery: 10

# https://www.home-assistant.io/integrations/group
group:
  plants:
    name: Plants
    entities:
      - plant.ficus
      - plant.basil
  batteries:
    name: Batteries
    entities:
      - sensor.thermostat_battery_percent
      - sensor.living_room_valve_battery_percent
      - sensor.bedroom_valve_battery_percent
      - sensor.tze200_c88teujp_ts0601_f262c3fe_power
      - sensor.lumi_sensor_motion_aq2_aeede202_power
      - sensor.lumi_sensor_magnet_0e017b02_power
      - sensor.lumi_sensor_magnet_eb017b02_power
      - sensor.lumi_sensor_magnet_ae874d05_power
      - sensor.ficus_battery

# https://www.home-assistant.io/integrations/weather
weather:
  # https://www.home-assistant.io/integrations/weather.darksky
  # https://darksky.net/dev/docs#response-format
  - platform: darksky
    api_key: !secret darksky_api_key

# https://www.home-assistant.io/integrations/ios
# https://companion.home-assistant.io
ios:

# https://www.home-assistant.io/integrations/notify
# https://companion.home-assistant.io/docs/notifications/notifications-basic
notify:
  # https://www.home-assistant.io/integrations/pushover
  - platform: pushover
    name: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

# https://www.home-assistant.io/integrations/tts
tts:
  # https://www.home-assistant.io/integrations/google_translate
  - platform: google_translate


# https://www.home-assistant.io/integrations/homekit
homekit:
  filter:
    include_entities:
      # Entryway
      # Livingroom
      - light.zha_group_0x0002
      - light.livingroom_floor_lamp
      - light.shelf
      - light.tv
      # Bedroom
      - light.ikea_tradfri_bulb_744e24fe_level_on_off

# https://www.home-assistant.io/integrations/logger
logger:
  default: warning
  # logs:
    # homeassistant.components.shelly: debug
    # custom_components.airco2ntrol: debug

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
