person.jan:
  entity_picture: /local/jansauer.jpg

# friendly light names
sensor.home_assistant_v2_db:
  friendly_name: Database size
light.gateway_light_7811dcfaea5b:
  friendly_name: Xiaomi Gateway Light
  icon: mdi:album
switch.wall_switch_158d000161469d:
  friendly_name: Entryway Ceiling Light
  icon: mdi:ceiling-light
light.livingroom_ceiling_lights:
  friendly_name: Livingroom Ceiling Lights
  icon: mdi:ceiling-light
light.ikea_tradfri_bulb_gu10_ws_400lm_1:
  friendly_name: Livingroom Ceiling Bulb 1
light.ikea_tradfri_bulb_gu10_ws_400lm_2:
  friendly_name: Livingroom Ceiling Bulb 2
light.ikea_tradfri_bulb_gu10_ws_400lm_3:
  friendly_name: Livingroom Ceiling Bulb 3
light.ikea_tradfri_bulb_gu10_ws_400lm_4:
  friendly_name: Livingroom Ceiling Bulb 4
light.livingroom_accent_lights:
  icon: mdi:group-work
light.ikea_tradfri_bulb_e27_opal_1000lm_1:
  friendly_name: Bedroom Ceiling Light
  icon: mdi:ceiling-light

sensor.lumi_lumi_remote_b286acn01_2c87f302_1_1:
  friendly_name: Livingroom Switch
sensor.lumi_lumi_remote_b286acn01_2c87f302_1_18:
  friendly_name: Livingroom Switch Left Single
sensor.lumi_lumi_remote_b286acn01_2c87f302_2_18:
  friendly_name: Livingroom Switch Right Single
sensor.lumi_lumi_remote_b286acn01_2c87f302_3_18:
  friendly_name: Livingroom Switch Both Single

# toggle switches for limitlessled lights
# @See https://www.home-assistant.io/components/light.limitlessled/#initialization--synchronization
light.tv:
  assumed_state: false
  icon: mdi:lamp
light.shelf:
  assumed_state: false
  icon: mdi:lamp
