person.jan:
  entity_picture: /local/jansauer.jpg

# friendly light names
light.gateway_light_7811dcfaea5b:
  friendly_name: Gateway Light
  icon: mdi:album
switch.wall_switch_158d000161469d:
  friendly_name: Ceiling
  icon: mdi:ceiling-light
light.livingroom_ceiling_lights:
  friendly_name: Ceiling
  icon: mdi:ceiling-light
light.livingroom_ceiling_bulb_1:
  friendly_name: Bulb 1
light.livingroom_ceiling_bulb_2:
  friendly_name: Bulb 2
light.livingroom_ceiling_bulb_3:
  friendly_name: Bulb 3
light.livingroom_ceiling_bulb_4:
  friendly_name: Bulb 4
light.livingroom_accent_lights:
  friendly_name: Accent
  icon: mdi:numeric-2-box-multiple-outline
light.bedroom_ceiling_bulb:
  friendly_name: Ceiling
  icon: mdi:ceiling-light

# toggle switches for limitlessled lights
# @See https://www.home-assistant.io/components/light.limitlessled/#initialization--synchronization
light.tv:
  assumed_state: false
  icon: mdi:lamp
light.shelf:
  assumed_state: false
  icon: mdi:lamp
