# https://www.home-assistant.io/docs/configuration/customizing-devices/

# Add Entity Pictures
person.jan:
  entity_picture: /local/jansauer.jpg
plant.sansevieria_cylindrica_boncel:
  entity_picture: /local/plants/sansevieria_cylindrica_boncel.jpg
plant.callisia_repens:
  entity_picture: /local/plants/callisia_repens.jpg
plant.ficus:
  entity_picture: /local/plants/ficus.jpg
plant.pteris:
  entity_picture: /local/plants/pteris.jpg
plant.basil:
  entity_picture: /local/plants/basil.jpg

# Set attributes for entities that do not have a unique ID
# No clue why this is the case but this prevents configuration via the UI
sensor.home_assistant_v2_db:
  friendly_name: Database size
switch.byss:
  icon: mdi:nas
light.livingroom_accent_lights:
  icon: mdi:lamp
light.livingroom_ceiling_lights:
  icon: mdi:ceiling-light

# Adopt missing attributes from zigbee group members
light.living_room_ceiling_lights_zha_group_0x0002:
  min_mireds: 250
  max_mireds: 454

# Fix missig toggle switches for limitlessled lights
# @See https://www.home-assistant.io/integrations/limitlessled#initialization--synchronization
light.tv:
  assumed_state: false
  icon: mdi:lamp
light.shelf:
  assumed_state: false
  icon: mdi:lamp

# Location tracking in Home Assistant zones
# https://companion.home-assistant.io/docs/core/location#ibeacons
zone.home:
  track_ios: true
  beacon:
    uuid: c214819c-0440-408a-87c7-1b16df0050c1
    major: 10167
    minor: 61921
