# hide byss device badge
device_tracker.byss:
  hidden: true

# hide tradfri battery badges
sensor.tradfri_motion_sensor:
  hidden: true
sensor.tradfri_remote_control:
  hidden: true
sensor.tradfri_wireless_dimmer:
  hidden: true

# hide plant badges
sensor.poinsettia_moisture:
  hidden: true
sensor.poinsettia_conductivity:
  hidden: true
sensor.poinsettia_light_intensity:
  hidden: true
sensor.poinsettia_temperature:
  hidden: true
sensor.poinsettia_battery:
  hidden: true

# hide blink battery and wifi badges
sensor.blink_home_battery:
  hidden: true
sensor.blink_home_wifi_signal:
  hidden: true

# friendly light names
light.livingroom_ceiling_lights:
  friendly_name: Ceiling
light.livingroom_ceiling_bulb_1:
  friendly_name: Bulb 1
light.livingroom_ceiling_bulb_2:
  friendly_name: Bulb 2
light.livingroom_ceiling_bulb_3:
  friendly_name: Bulb 3
light.livingroom_ceiling_bulb_4:
  friendly_name: Bulb 4
light.livingroom_accent_lights:
  friendly_name: Accent
light.bedroom_ceiling_bulb:
  friendly_name: Ceiling

# toggle switches for limitlessled lights
# @See https://www.home-assistant.io/components/light.limitlessled/#initialization--synchronization
light.tv:
  assumed_state: false
light.shelf:
  assumed_state: false
