entryway:
  name: Entryway
  entities:
    - switch.wall_switch_158d000161469d

livingroom:
  name: Livingroom
  entities:
    - light.livingroom_accent_lights
    - light.shelf
    - light.tv

bedroom:
  name: Bedroom
  entities:
    -  light.gateway_light_7811dcfaea5b
