bedroom:
  name: Bedroom
  entities:
    - light.bedroom_ceiling_bulb

livingroom:
  name: Livingroom
  entities:
    - light.livingroom_ceiling_lights
    - light.livingroom_ceiling_bulb_1
    - light.livingroom_ceiling_bulb_2
    - light.livingroom_ceiling_bulb_3
    - light.livingroom_ceiling_bulb_4
    - light.livingroom_accent_lights
    - light.shelf
    - light.tv
