- name: Livingroom Night Light
  entities:
    light.tv:
      state: on
      effect: night
    light.shelf:
      state: on
      effect: night

- name: Livingroom Off
  entities:
    light.livingroom_ceiling_lights:
      state: off
    switch.osram_plug_1:
      state: off
    light.livingroom_accent_lights:
      state: off

# - name: Bedroom Night Light
#   entities:
#     light.tv:
#       state: on
#       effect: night

- name: Bedroom Off
  entities:
    light.ikea_tradfri_bulb_e27_opal_1000lm_1:
      state: off
    light.gateway_light_7811dcfaea5b:
      state: off
