return_home:
  sequence:
    - service: notify.notify
      data:
        message: 'Wellcome Home!'
    - service: climate.set_preset_mode
      data:
        entity_id: climate.netatmo_living_room
        preset_mode: Schedule
    - service: climate.set_preset_mode
      data:
        entity_id: climate.netatmo_bedroom
        preset_mode: Schedule
