title: Insides
resources:
  # https://github.com/maykar/custom-header
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  # https://github.com/thomasloven/lovelace-layout-card
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
custom_header:
  compact_mode: true
views:
  - title: Insides
    path: insides
    icon: mdi:stethoscope
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: glance
            title: System
            entities:
              - sensor.load_1m
              - sensor.load_5m
              - sensor.load_15m
              - sensor.disk_free
              - sensor.memory_free
              - sensor.home_assistant_v2_db
              - sensor.uptime
              - sensor.time
              - binary_sensor.updater
              - sensor.hacs
          - type: glance
            title: Environment
            entities:
              - entity: sensor.yr_symbol
                name: YR
              - weather.home
              - sun.sun
              - sensor.moon
              - binary_sensor.iss
          - type: entities
            title: People
            entities:
              - person.jansauer
          - type: map
            entities:
              - device_tracker.iphonex
              - device_tracker.watch
              - device_tracker.ipadpro
            aspect_ratio: 16:9
            default_zoom: 15
            # dark_mode: true
            hours_to_show: 48
          - break
          - type: entities
            title: Trådfri (ZHA)
            show_header_toggle: false
            entities:
              # livingroom Ceiling Bulbs
              - light.ikea_tradfri_bulb_gu10_ws_400lm_1
              - light.ikea_tradfri_bulb_gu10_ws_400lm_2
              - light.ikea_tradfri_bulb_gu10_ws_400lm_3
              - light.ikea_tradfri_bulb_gu10_ws_400lm_4
              # Bedroom Ceiling Light
              - light.ikea_tradfri_bulb_e27_opal_1000lm_1
          - type: entities
            title: Osram (ZHA)
            show_header_toggle: false
            entities:
              - switch.osram_plug_1
              - sensor.osram_plug_1
          - type: entities
            title: Xiaomi (ZHA)
            show_header_toggle: false
            entities:
              # Entryway Motion Sensor
              - sensor.illumination_7811dcfaea5b
              - type: divider
              # Livingroom Door
              - binary_sensor.lumi_lumi_sensor_magnet_0e017b02_on_off
              - sensor.lumi_lumi_sensor_magnet_0e017b02_power
              - type: divider
              # Livingroom Switch
              - sensor.lumi_lumi_remote_b286acn01_2c87f302_1
              - sensor.lumi_lumi_remote_b286acn01_2c87f302_2
              - sensor.lumi_lumi_remote_b286acn01_2c87f302_3
              - sensor.lumi_lumi_remote_b286acn01_2c87f302_power
              - type: divider
              # Bedroom Window
              - binary_sensor.lumi_lumi_sensor_magnet_eb017b02_1_6
              - sensor.lumi_lumi_sensor_magnet_eb017b02_1_1
          - type: entities
            title: Xiaomi
            show_header_toggle: false
            entities:
              - light.gateway_light_7811dcfaea5b
              - switch.wall_switch_158d000161469d
          - type: entities
            title: LimitlessLED
            show_header_toggle: false
            entities:
              - light.tv
              - light.shelf
          - break
          - type: glance
            title: AirCO2ntrol
            entities:
              - entity: sensor.airco2ntrol_temperature
                name: Temperature
              - entity: sensor.airco2ntrol_carbon_dioxide
                name: Carbon Dioxide
          - type: glance
            title: Withings
            entities:
              - entity: sensor.withings_weight_kg
                name: Weight
              - entity: sensor.withings_fat_free_mass_kg
                name: Fat Free Mass
              - entity: sensor.withings_fat_mass_kg
                name: Fat Mass
              - entity: sensor.withings_fat_ratio_pct
                name: Fat Ratio
              - entity: sensor.withings_heart_pulse_bpm
                name: Heart Rate
          - type: weather-forecast
            entity: weather.dark_sky
          - break
          - type: thermostat
            entity: climate.netatmo_living_room
          - type: thermostat
            entity: climate.netatmo_bedroom
          - type: glance
            title: Blink
            entities:
              - entity: binary_sensor.blink_home_motion_detected
                name: Motion Detected
              - entity: binary_sensor.blink_home_camera_armed
                name: Camera Armed
              - entity: sensor.blink_home_temperature
                name: Temperature
              - entity: sensor.blink_home_wifi_signal
                name: Wifi Signal
              - entity: binary_sensor.blink_home_battery
                name: Battery
          - entity: camera.blink_home
            type: picture-entity
          - type: alarm-panel
            entity: alarm_control_panel.blink_blink

  - title: Media
    path: media
    icon: mdi:cast
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: media-control
            entity: media_player.spotify
          - type: media-control
            entity: media_player.living_room_chromecast
          - type: media-control
            entity: media_player.plex_plex_for_apple_tv_living_room
          - type: media-control
            entity: media_player.plex_plex_cast_chromecast
          - type: media-control
            entity: media_player.plex_plex_web_chrome_osx

  - title: Devices
    path: devices
    icon: mdi:router-wireless
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: glance
            title: Device
            entities:
              - device_tracker.iphonex
              - device_tracker.watch
              - device_tracker.ipadpro
              - device_tracker.macbookpro
              - device_tracker.byss
              - device_tracker.netatmo
              - device_tracker.xiaomi
              - device_tracker.limitlessled
              - device_tracker.blink
              - device_tracker.echodot
          - type: entities
            title: Alderaan
            show_header_toggle: false
            entities:
              - entity: sensor.alderaan_bytes_received
                name: Bytes received
              - entity: sensor.alderaan_bytes_sent
                name: Bytes sent
              - entity: sensor.alderaan_kib_sec_received
                name: KiB/s received
              - entity: sensor.alderaan_kib_sec_sent
                name: KiB/s send
              - entity: sensor.alderaan_packets_received
                name: Packets received
              - entity: sensor.alderaan_packets_sent
                name: Packets sent
              - entity: sensor.alderaan_packets_sec_received
                name: Packets/s received
              - entity: sensor.alderaan_packets_sec_sent
                name: Packets/s sent
          - break
          - type: glance
            title: Sleepy (ESPHome)
            entities:
              - binary_sensor.sleepy_status
              - sensor.sleepy_uptime
              - sensor.sleepy_esphome_version
              - sensor.sleepy_wifi_signal
              # - sensor.sleepy_temperature
              # - sensor.sleepy_humidity
              - binary_sensor.sleepy_motion_left
              - light.sleepy_strip
          - type: glance
            title: Windy (ESPHome)
            entities:
              - binary_sensor.windy_status
              - sensor.windy_uptime
              - sensor.windy_esphome_version
              - sensor.windy_wifi_signal
              - switch.windy_shutdown
              - sensor.windy_temperature
              - sensor.windy_humidity
              - sensor.windy_pm_2_5
              - sensor.windy_pm_10_0
          - break
          - type: entities
            title: iPhone X
            show_header_toggle: false
            entities:
              - device_tracker.iphone_x
              - entity: sensor.iphone_x_geocoded_location
                name: Geocoded Location
              - entity: sensor.iphone_x_activity
                name: Activity
              - entity: sensor.iphone_x_average_active_pace
                name: Average Active Pace
              - entity: sensor.iphone_x_distance
                name: Distance
              - entity: sensor.iphone_x_steps
                name: Steps
              - entity: sensor.iphone_x_floors_ascended
                name: Floors Ascended
              - entity: sensor.iphone_x_floors_descended
                name: Floors Descended
              - entity: sensor.iphone_x_storage
                name: Storage
              - entity: sensor.iphone_x_ssid
                name: SSID
              - entity: sensor.iphone_x_bssid
                name: BSSID
              - entity: sensor.iphone_x_sim_1
                name: SIM 1
              - entity: sensor.iphone_x_battery_state
                name: Battery State
              - entity: sensor.iphone_x_battery_level
                name: Battery Level
              - entity: sensor.iphone_x_connection_type
                name: Connection Type
              - entity: sensor.iphone_x_last_update_trigger
                name: Last Update Trigger
          - type: entities
            title: iPad Pro
            show_header_toggle: false
            entities:
              - device_tracker.ipad
              - entity: sensor.ipad_geocoded_location
                name: Geocoded Location
              - entity: sensor.ipad_activity
                name: Activity
              - entity: sensor.ipad_storage
                name: Storage
              - entity: sensor.ipad_ssid
                name: SSID
              - entity: sensor.ipad_bssid
                name: BSSID
              - entity: sensor.ipad_battery_state
                name: Battery State
              - entity: sensor.ipad_battery_level
                name: Battery Level
              - entity: sensor.ipad_connection_type
                name: Connection Type
              - entity: sensor.ipad_last_update_trigger
                name: Last Update Trigger

  # - title: Environment
  #   path: environment
  #   icon: mdi:weather-rainy
  #   panel: true
  #   cards:
  #     - type: custom:layout-card
  #       layout: vertical
  #       cards:

  - title: Automation
    path: automation
    icon: mdi:robot
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: entities
            title: Automations
            show_header_toggle: false
            entities:
              - automation.leaving_home
              - automation.returning_home
              - type: divider
              - automation.turn_on_entryway_light_when_there_is_movement
              - automation.turn_off_entryway_lights_after_movement
              - type: divider
              - automation.livingroom_wall_switch_left_single
              - automation.livingroom_wall_switch_right_single
              - automation.livingroom_wall_switch_right_double
              - type: divider
              - automation.set_theme_for_day_and_night
              - automation.plant_problem_notifications
          - break
          - type: entities
            title: Scripts
            show_header_toggle: false
            entities:
              - script.return_home
          - type: entities
            title: Scripts
            show_header_toggle: false
            entities:
              - scene.livingroom_work
              - scene.livingroom_night_light
              - scene.livingroom_off
              - scene.bedroom_off
          - type: entities
            title: Inputs
            show_header_toggle: false
            entities:
              - input_boolean.mode_guest_mode
          - break
          - type: entities
            title: Wake-up Lights
            show_header_toggle: false
            entities:
              - input_datetime.wakeup_time
              - entity: automation.wake_me_up_using_bedroom_lights
                name: "Wake-up lights"
                icon: mdi:theme-light-dark
              - input_boolean.wakeup_weekend

  - title: Test
    path: test
    icon: mdi:test-tube
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: glance
            title: Snow Flower
            entities:
              - entity: sensor.snowflower_moisture
                name: Moisture
              - entity: sensor.snowflower_conductivity
                name: Conductivity
              - entity: sensor.snowflower_light_intensity
                name: Light Intensity
              - entity: sensor.snowflower_temperature
                name: Temperature
              - entity: sensor.snowflower_battery
                name: Battery
          - break
          - type: glance
            title: Balcony Flowers
            entities:
              - entity: sensor.balcony_moisture
                name: Moisture
              - entity: sensor.balcony_conductivity
                name: Conductivity
              - entity: sensor.balcony_light_intensity
                name: Light Intensity
              - entity: sensor.balcony_temperature
                name: Temperature
              - entity: sensor.balcony_battery
                name: Battery
          - type: plant-status
            entity: plant.balcony
