title: Insides
# resources:
#   # https://github.com/maykar/custom-header
#   - url: /hacsfiles/custom-header/custom-header.js
#     type: module
#   # https://github.com/thomasloven/lovelace-layout-card
#   - url: /hacsfiles/lovelace-layout-card/layout-card.js
#     type: module
#   # https://github.com/maxwroc/battery-state-card
#   - url: /hacsfiles/battery-state-card/battery-state-card.js
#     type: module
#   - url: /local/zha-network-visualization-card/zha-network-visualization-card.js
#     type: module
#   - url: /local/flower-card/flower-card.js
#     type: module
custom_header:
  compact_mode: true
views:
  - title: Insides
    path: insides
    icon: mdi:stethoscope
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: glance
            title: System
            entities:
              - sensor.load_1m
              - sensor.load_5m
              - sensor.load_15m
              - sensor.disk_free
              - sensor.memory_free
              - sensor.home_assistant_v2_db
              - sensor.uptime
              - sensor.time
              - binary_sensor.updater
              - sensor.hacs
          - type: entities
            entities:
              - binary_sensor.rpi_power_status
          - break
          - type: entities
            title: People
            entities:
              - person.jansauer
          - type: map
            aspect_ratio: 16:9
            default_zoom: 15
            # dark_mode: true
            hours_to_show: 48
            entities:
              - zone.home
              - device_tracker.iphone_x
          - type: glance
            title: Withings
            entities:
              - entity: sensor.withings_weight_kg
                name: Weight
              - entity: sensor.withings_fat_free_mass_kg
                name: Fat Free Mass
              - entity: sensor.withings_fat_mass_kg
                name: Fat Mass
              - entity: sensor.withings_fat_ratio_pct
                name: Fat Ratio
              - entity: sensor.withings_heart_pulse_bpm
                name: Heart Rate
          - break
          - type: markdown
            content: >
              ## Spotify
          - type: media-control
            entity: media_player.spotify_1174358001
          - type: markdown
            content: >
              ## Apple TV
          - type: media-control
            entity: media_player.living_room
          - type: markdown
            content: >
              ## Chromecast
          - type: media-control
            entity: media_player.living_room_chromecast
          - type: markdown
            content: >
              ## Plex
          - type: media-control
            entity: media_player.plex_plex_for_apple_tv_living_room
          - type: media-control
            entity: media_player.plex_plex_cast_chromecast
          - type: media-control
            entity: media_player.plex_plex_web_chrome_osx

  - title: InputOutput
    path: input-output
    icon: mdi:dip-switch
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: glance
            title: AirCO2ntrol
            entities:
              - entity: sensor.airco2ntrol_temperature
                name: Temperature
              - entity: sensor.airco2ntrol_carbon_dioxide
                name: Carbon Dioxide
          - type: entities
            title: LimitlessLED
            show_header_toggle: false
            entities:
              - light.tv
              - light.shelf
          - type: entities
            title: Shelly
            show_header_toggle: false
            entities:
              - switch.shelly_shsw_25_483fda4ce546_1
              - sensor.shelly_shsw_25_483fda4ce546_1_current_consumption
              - binary_sensor.shelly_shsw_25_483fda4ce546_1_switch
              - switch.shelly_shsw_25_483fda4ce546_2
              - sensor.shelly_shsw_25_483fda4ce546_2_current_consumption
              - binary_sensor.shelly_shsw_25_483fda4ce546_2_switch
              - entity: switch.shelly_shsw_25_483fda4ce546_firmware_update
              - type: divider
              - switch.shelly_shsw_25_40f520015f98_1
              - sensor.shelly_shsw_25_40f520015f98_1_current_consumption
              - binary_sensor.shelly_shsw_25_40f520015f98_1_switch
              - switch.shelly_shsw_25_40f520015f98_2
              - sensor.shelly_shsw_25_40f520015f98_2_current_consumption
              - binary_sensor.shelly_shsw_25_40f520015f98_2_switch
              - switch.shelly_shsw_25_40f520015f98_firmware_update
          - break
          - type: entities
            title: Trådfri (ZHA)
            show_header_toggle: false
            entities:
              # livingroom Ceiling Bulbs
              - light.ikea_tradfri_bulb_gu10_ws_400lm_1
              - light.ikea_tradfri_bulb_gu10_ws_400lm_2
              - light.ikea_tradfri_bulb_gu10_ws_400lm_3
              - light.ikea_tradfri_bulb_gu10_ws_400lm_4
              # Bedroom Ceiling Light
              - light.ikea_tradfri_bulb_e27_opal_1000lm_1
              # Switch
              - sensor.ikea_of_sweden_tradfri_on_off_switch_739c78fe_power
              - sensor.ikea_of_sweden_tradfri_remote_control_3230dcfe_power
          - type: entities
            title: Osram (ZHA)
            show_header_toggle: false
            entities:
              - switch.osram_plug_1
              - sensor.osram_plug_1
              - light.livingroom_floor_lamp
          - type: entities
            title: Xiaomi (ZHA)
            show_header_toggle: false
            entities:
              # Entryway Motion Sensor
              - binary_sensor.lumi_lumi_sensor_motion_aq2_aeede202_occupancy
              - binary_sensor.lumi_lumi_sensor_motion_aq2_aeede202_ias_zone
              - sensor.lumi_lumi_sensor_motion_aq2_aeede202_illuminance
              - sensor.lumi_lumi_sensor_motion_aq2_aeede202_power
              - type: divider
              # Livingroom Door
              - binary_sensor.lumi_lumi_sensor_magnet_0e017b02
              - sensor.lumi_lumi_sensor_magnet_0e017b02_power
              - type: divider
              # Bedroom Window
              - binary_sensor.lumi_lumi_sensor_magnet_eb017b02
              - sensor.lumi_lumi_sensor_magnet_eb017b02_power
          - break
          - type: glance
            title: Windy (ESPHome)
            entities:
              - entity: binary_sensor.windy_status
                name: Status
              - entity: sensor.windy_uptime
                name: Uptime
              - entity: sensor.windy_wifi_signal
                name: Wifi
              - entity: sensor.windy_temperature
                name: Temperature
              - entity: sensor.windy_humidity
                name: Humidity
              - entity: sensor.windy_pm_10_0
                name: PM 10.0
              - entity: sensor.windy_pm_2_5
                name: PM 2.5
          - type: glance
            title: Sleepy (ESPHome)
            entities:
              - entity: binary_sensor.sleepy_status
                name: Status
              - entity: sensor.sleepy_uptime
                name: Uptime
              - entity: sensor.sleepy_wifi_signal
                name: Wifi
              # - sensor.sleepy_temperature
              # - sensor.sleepy_humidity
              - entity: binary_sensor.sleepy_motion_left
                name: Motion Left
              - entity: light.sleepy_strip
                name: Strip

  - title: Climate
    path: climate
    icon: mdi:home-thermometer-outline
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: thermostat
            entity: climate.netatmo_living_room
          - type: thermostat
            entity: climate.netatmo_bedroom

  - title: Plants
    path: plants
    icon: mdi:sprout
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: glance
            title: Sansevieria Cylindrica Boncel
            entities:
              - entity: sensor.sansevieria_cylindrica_boncel_moisture
                name: Moisture
              - entity: sensor.sansevieria_cylindrica_boncel_temperature
                name: Temperature
              - entity: sensor.sansevieria_cylindrica_boncel_light_intensity
                name: Light Intensity
              - entity: sensor.sansevieria_cylindrica_boncel_conductivity
                name: Conductivity
              - entity: sensor.sansevieria_cylindrica_boncel_battery
                name: Battery
          - type: plant-status
            entity: plant.sansevieria_cylindrica_boncel
          - break
          - type: glance
            title: Callisia Repens
            entities:
              - entity: sensor.callisia_repens_moisture
                name: Moisture
              - entity: sensor.callisia_repens_temperature
                name: Temperature
              - entity: sensor.callisia_repens_light_intensity
                name: Light Intensity
              - entity: sensor.callisia_repens_conductivity
                name: Conductivity
              - entity: sensor.callisia_repens_battery
                name: Battery
          - type: plant-status
            entity: plant.callisia_repens
          - break
          - type: glance
            title: Fiscus
            entities:
              - entity: sensor.ficus_moisture
                name: Moisture
              - entity: sensor.ficus_temperature
                name: Temperature
              - entity: sensor.ficus_light_intensity
                name: Light Intensity
              - entity: sensor.ficus_conductivity
                name: Conductivity
              - entity: sensor.ficus_battery
                name: Battery
          - type: plant-status
            entity: plant.ficus
          - break
          - type: glance
            title: Pteris
            entities:
              - entity: sensor.pteris_moisture
                name: Moisture
              - entity: sensor.pteris_temperature
                name: Temperature
              - entity: sensor.pteris_light_intensity
                name: Light Intensity
              - entity: sensor.pteris_conductivity
                name: Conductivity
              - entity: sensor.pteris_battery
                name: Battery
          - type: plant-status
            entity: plant.pteris
          - break
          - type: glance
            title: Basil
            entities:
              - entity: sensor.basil_moisture
                name: Moisture
              - entity: sensor.basil_temperature
                name: Temperature
              - entity: sensor.basil_light_intensity
                name: Light Intensity
              - entity: sensor.basil_conductivity
                name: Conductivity
              - entity: sensor.basil_battery
                name: Battery
          - type: plant-status
            entity: plant.basil

  - title: Environment
    path: environment
    icon: mdi:weather-partly-cloudy
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: weather-forecast
            entity: weather.home
          - type: glance
            title: Deutscher Wetterdienst
            entities:
              - entity: sensor.dwd_weather_warnings_current_warning_level
                name: Current Warning Level
              - entity: sensor.dwd_weather_warnings_advance_warning_level
                name: Advance Warning Level
          - break
          - type: glance
            title: Celestial
            entities:
              - sun.sun
              - sensor.moon
              - binary_sensor.iss

  - title: Devices
    path: devices
    icon: mdi:devices
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: glance
            title: Device
            entities:
              - device_tracker.iphonex
              - device_tracker.watch
              - device_tracker.ipadpro
              - device_tracker.macbookpro
              - device_tracker.byss
              - device_tracker.netatmo
              - device_tracker.limitlessled
              - device_tracker.blink
              - device_tracker.echodot
          - type: entities
            title: NAS
            show_header_toggle: false
            entities:
              - switch.byss
          - break
          - type: entities
            title: iPhone X
            show_header_toggle: false
            entities:
              - device_tracker.iphone_x
              - entity: sensor.iphone_x_geocoded_location
                name: Geocoded Location
              - entity: sensor.iphone_x_activity
                name: Activity
              - entity: sensor.iphone_x_average_active_pace
                name: Average Active Pace
              - entity: sensor.iphone_x_distance
                name: Distance
              - entity: sensor.iphone_x_steps
                name: Steps
              - entity: sensor.iphone_x_floors_ascended
                name: Floors Ascended
              - entity: sensor.iphone_x_floors_descended
                name: Floors Descended
              - entity: sensor.iphone_x_storage
                name: Storage
              - entity: sensor.iphone_x_ssid
                name: SSID
              - entity: sensor.iphone_x_bssid
                name: BSSID
              - entity: sensor.iphone_x_sim_1
                name: SIM 1
              - entity: sensor.iphone_x_battery_state
                name: Battery State
              - entity: sensor.iphone_x_battery_level
                name: Battery Level
              - entity: sensor.iphone_x_connection_type
                name: Connection Type
              - entity: sensor.iphone_x_last_update_trigger
                name: Last Update Trigger
          - break
          - type: entities
            title: iPad Pro
            show_header_toggle: false
            entities:
              - device_tracker.ipad
              - entity: sensor.ipad_geocoded_location
                name: Geocoded Location
              - entity: sensor.ipad_activity
                name: Activity
              - entity: sensor.ipad_storage
                name: Storage
              - entity: sensor.ipad_ssid
                name: SSID
              - entity: sensor.ipad_bssid
                name: BSSID
              - entity: sensor.ipad_battery_state
                name: Battery State
              - entity: sensor.ipad_battery_level
                name: Battery Level
              - entity: sensor.ipad_connection_type
                name: Connection Type
              - entity: sensor.ipad_last_update_trigger
                name: Last Update Trigger

  - title: Security
    path: security
    icon: mdi:cctv
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: glance
            title: Blink
            entities:
              - entity: binary_sensor.blink_home_motion_detected
                name: Motion Detected
              - entity: binary_sensor.blink_home_camera_armed
                name: Camera Armed
              - entity: sensor.blink_home_temperature
                name: Temperature
              - entity: sensor.blink_home_wifi_signal
                name: Wifi Signal
              - entity: binary_sensor.blink_home_battery
                name: Battery
          - entity: camera.blink_home
            type: picture-entity
          - type: alarm-panel
            entity: alarm_control_panel.blink_blink
          - type: entities
            title: Script
            show_header_toggle: false
            entities:
              - script.blink_trigger_camera

  - title: Automation
    path: automation
    icon: mdi:robot
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: entities
            title: Automations
            show_header_toggle: false
            entities:
              - automation.leaving_home
              - automation.returning_home
              - type: divider
              - automation.wall_switch_living_room_left_single_click
              - automation.wall_switch_living_room_right_single_click
              - type: divider
              - automation.wall_switch_bedroom_left_single_click
              - type: divider
              - automation.open_window_notifications
              - automation.plant_problem_notifications
              - automation.plant_problem_remainder_notifications
              - type: divider
              - automation.set_theme_for_day_and_night
          - break
          - type: entities
            title: Scenes
            show_header_toggle: false
            entities:
              - scene.livingroom_work
              - scene.livingroom_night_light
              - scene.livingroom_off
              - scene.bedroom_off
          - type: entities
            title: Script
            show_header_toggle: false
            entities:
              - script.blink_trigger_camera
          - type: entities
            title: Inputs
            show_header_toggle: false
            entities:
              - input_boolean.mode_guest_mode
          - type: entities
            title: Groups
            show_header_toggle: false
            entities:
              - light.livingroom_ceiling_lights
              - light.livingroom_accent_lights
              - group.plants
          - break
          - type: entities
            title: Wake-up Lights
            show_header_toggle: false
            entities:
              - input_datetime.wakeup_time
              - entity: automation.wake_me_up_using_bedroom_lights
                name: "Wake-up lights"
                icon: mdi:theme-light-dark
              - input_boolean.wakeup_weekend
          - type: custom:battery-state-card
            title: Battery Level
            sort_by_level: "asc"
            filter:
              include:
                - name: entity_id
                  value: "*_battery"
                - name: entity_id
                  value: "*_power"
            entities:
              - climate.netatmo_living_room
              - climate.netatmo_bedroom
              # - sensor.ikea_of_sweden_tradfri_remote_control_3230dcfe_power
              # - sensor.lumi_lumi_sensor_magnet_0e017b02_power
              # - sensor.lumi_lumi_sensor_magnet_eb017b02_power

  # - title: Test
  #   path: test
  #   icon: mdi:test-tube
  #   panel: true
  #   cards:
