title: Home
resources:
  # https://momentjs.com/
  - url: /local/moment.js?v=2.24.0
    type: js
  # https://github.com/maykar/compact-custom-header
  - url: /local/compact-custom-header.js?v=68a6e202
    type: module
  # https://github.com/thomasloven/lovelace-card-tools
  - url: /local/card-tools.js?v=d6b209b4
    type: js
  # https://github.com/thomasloven/lovelace-card-mod
  - url: /local/card-mod.js?v=ebc779f
    type: module
  # https://github.com/thomasloven/lovelace-layout-card
  - url: /local/layout-card.js?v=3364e158
    type: js
  # https://github.com/nervetattoo/simple-thermostat
  - url: /local/simple-thermostat.js?v=0.29.0
    type: module
  # https://github.com/kalkih/mini-graph-card
  - url: /local/mini-graph-card-bundle.js?v=0.8.2
    type: module
  - url: /local/clock-card.js?v=0.0.8
    type: js
  - url: /local/daytime-card/daytime-card.js?v=0.0.217
    type: js
cch:
  conditional_styles:
    - entity: group.all_plants
      condition:                     
        state: problem
      tab:
        2:
          color: rgb(244, 179, 170)
background: var(--background-image)
views:

  - title: Overview
    path: overview
    icon: mdi:one-up
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_columns: 3
        cards:
          - type: custom:clock-card
            entity: person.jan
          - type: custom:daytime-card
            entity: sun.sun
          - type: weather-forecast
            entity: weather.dark_sky
          - break
          - type: horizontal-stack
            cards:
              - type: entities
                title: Entryway
                show_header_toggle: true
                entities:
                  - entity: switch.wall_switch_158d000161469d
                    name: Ceiling
          - type: custom:simple-thermostat
            entity: climate.netatmo_living_room
            name: Livingroom
            icon: false
            control: false
            sensors:
              - entity: climate.netatmo_living_room
                attribute: preset_mode
                name: Mode
            style:
            style: |
              ha-card {
                --st-font-size-xl: 30px;
                --st-font-size-m: 20px;
                --st-font-size-sensors: 14px;
                --st-spacing: 2px;
              }
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: light.livingroom_ceiling_lights
                    name: Ceiling
                  - entity: switch.osram_plug_1
                    name: Floor Lamp
                    icon: mdi:floor-lamp
                  - entity: light.livingroom_accent_lights
                    name: Accent
                  - light.tv
                  - light.shelf
              - type: vertical-stack
                cards:
                  - type: custom:mini-graph-card
                    name: Temperature
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    lower_bound: 15
                    line_color: '#FFC107'
                    entities:
                      - sensor.airco2ntrol_temperature
                  - type: custom:mini-graph-card
                    name: Carbon Dioxide
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    line_color: '#9C27B0'
                    entities:
                      - sensor.airco2ntrol_carbon_dioxide
          - type: horizontal-stack
            cards:
              - type: entities
                title: Bedroom
                show_header_toggle: true
                entities:
                  - entity: light.ikea_tradfri_bulb_e27_opal_1000lm_1
                    name: Ceiling
                  - entity: light.gateway_light_7811dcfaea5b
                    name: Gateway
              - type: vertical-stack
                cards:
                  - type: custom:mini-graph-card
                    name: Temperature
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    lower_bound: 12
                    line_color: '#FFC107'
                    entities:
                      - entity: sensor.sleepy_temperature
                        name: Temperature
                  - type: custom:mini-graph-card
                    name: Humidity
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    line_color: '#03A9F4'
                    entities:
                      - entity: sensor.sleepy_humidity
                        name: Humidity
          - break
          - type: media-control
            entity: media_player.spotify
          - type: media-control
            entity: media_player.living_room

  - title: Floor plan
    path: floorplan
    icon: mdi:map
    panel: true
    cards:
      - type: custom:layout-card
        layout: horizontal
        max_width:
          - 27%
          - 73%
        cards:
          - type: picture-elements
            image: /local/floorplan.png
            elements:
              - type: state-icon
                tap_action:
                  action: toggle
                entity: light.shelf
                style:
                  top: 47%
                  left: 42%
              - type: state-icon
                tap_action:
                  action: toggle
                entity: light.gateway_light_7811dcfaea5b
                style:
                  top: 50%
                  left: 4%

  - title: Plants
    path: plants
    icon: mdi:leaf
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_columns: 3
        cards:
          - type: custom:daytime-card
            entity: sun.sun
          - type: weather-forecast
            entity: weather.dark_sky
          - break
          - type: plant-status
            entity: plant.snowflower
          - type: plant-status
            entity: plant.balcony

  - title: Insides
    path: insides
    icon: mdi:stethoscope
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_columns: 3
        cards:
          - type: glance
            title: System
            entities:
              - sensor.load_1m
              - sensor.load_5m
              - sensor.load_15m
              - sensor.disk_free
              - sensor.memory_free
              - sensor.home_assistant_v2_db
              - sensor.uptime
              - sensor.time
              - binary_sensor.updater
          - type: glance
            title: Devices
            entities:
              - device_tracker.ipadpro
              - device_tracker.iphonex
              - device_tracker.macbookpro
              - device_tracker.byss
          - type: horizontal-stack
            cards:
              - type: glance
                title: iPhone X
                entities:
                  - entity: sensor.iphone_x_battery_level
                    name: Level
                  - entity: sensor.iphone_x_battery_state
                    name: State
              - type: glance
                title: iPad
                entities:
                  - entity: sensor.ipad_pro_battery_level
                    name: Level
                  - entity: sensor.ipad_pro_battery_state
                    name: State
          - type: glance
            title: Environment
            entities:
              - sun.sun
              - sensor.moon
              - entity: sensor.yr_symbol
                name: YR
              - binary_sensor.iss
          - type: glance
            title: AirCO2ntrol
            entities:
              - entity: sensor.airco2ntrol_temperature
                name: Temperature
              - entity: sensor.airco2ntrol_carbon_dioxide
                name: Carbon Dioxide
          - break
          - type: glance
            title: Trådfri (ZHA)
            entities:
              - light.ikea_tradfri_bulb_gu10_ws_400lm_1
              - light.ikea_tradfri_bulb_gu10_ws_400lm_2
              - light.ikea_tradfri_bulb_gu10_ws_400lm_3
              - light.ikea_tradfri_bulb_gu10_ws_400lm_4
              - light.ikea_tradfri_bulb_e27_opal_1000lm_1
          - type: glance
            title: Osram (ZHA)
            entities:
              - switch.osram_plug_1
              - sensor.osram_plug_1
          - type: glance
            title: Sleepy (ESPHome)
            entities:
              - binary_sensor.sleepy_status
              - sensor.sleepy_uptime
              - sensor.sleepy_temperature
              - sensor.sleepy_humidity
              - sensor.sleepy_wifi_signal
          - type: glance
            title: Xiaomi
            entities:
              - binary_sensor.motion_sensor_158d0002e2edae
              - sensor.illumination_158d0002e2edae
              - binary_sensor.door_window_sensor_158d00027b010e
              - sensor.illumination_7811dcfaea5b
          - type: glance
            title: Snow Flower
            entities:
              - entity: sensor.snowflower_moisture
                name: Moisture
              - entity: sensor.snowflower_conductivity
                name: Conductivity
              - entity: sensor.snowflower_light_intensity
                name: Light Intensity
              - entity: sensor.snowflower_temperature
                name: Temperature
              - entity: sensor.snowflower_battery
                name: Battery
          - type: glance
            title: Balcony Flowers
            entities:
              - entity: sensor.balcony_moisture
                name: Moisture
              - entity: sensor.balcony_conductivity
                name: Conductivity
              - entity: sensor.balcony_light_intensity
                name: Light Intensity
              - entity: sensor.balcony_temperature
                name: Temperature
              - entity: sensor.balcony_battery
                name: Battery
          - break
          - type: glance
            title: Blink
            entities:
              - entity: binary_sensor.blink_home_motion_detected
                name: Motion Detected
              - entity: binary_sensor.blink_home_camera_armed
                name: Camera Armed
              - entity: sensor.blink_home_temperature
                name: Temperature
              - entity: sensor.blink_home_wifi_signal
                name: Wifi Signal
              - entity: sensor.blink_home_battery
                name: Battery
          - entity: camera.blink_home
            type: picture-entity
          - type: alarm-panel
            entity: alarm_control_panel.blink_sync
          - type: entities
            title: Automations
            show_header_toggle: false
            entities:
              - automation.set_theme_for_day_and_night
              - automation.update_available_notifications
              - automation.plant_problem_notifications

  - title: Test
    path: test
    icon: mdi:test-tube
    cards:
      - type: entities
        title: Wake-up Lights
        show_header_toggle: false
        entities:
          - input_datetime.wakeup_time
          - entity: automation.wake_me_up_using_bedroom_lights
            name: "Wake-up lights"
            icon: mdi:theme-light-dark
          - input_boolean.wakeup_weekend
      - type: entities
        title: Entryway Light Automation
        show_header_toggle: false
        entities:
          - entity: automation.turn_on_entryway_light_when_there_is_movement
            name: On Automation
          - entity: automation.turn_off_entryway_lights_after_movement
            name: Off Automation
          - timer.entryway
