# https://www.home-assistant.io/lovelace/
title: Home
custom_header:
  compact_mode: true
  conditional_styles:
    - entity: group.all_plants
      condition:                     
        state: problem
      tab:
        2:
          color: rgb(244, 179, 170)
background: var(--background-image)
views:

  - title: Overview
    path: overview
    icon: mdi:one-up
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_columns: 3
        cards:
          # - type: custom:clock-card
          #   entity: person.jan
          # - type: custom:daytime-card
          #   entity: sun.sun
          - type: weather-forecast
            entity: weather.dark_sky
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temperature
                hours_to_show: 6
                points_per_hour: 4
                hour24: true
                line_color: '#FFC107'
                entities:
                  - entity: sensor.windy_temperature
                    name: Temperature
                  - entity: sensor.windy_pm_2_5
                    name: Humidity
              - type: custom:mini-graph-card
                name: Humidity
                hours_to_show: 6
                points_per_hour: 4
                hour24: true
                line_color: '#03A9F4'
                entities:
                  - entity: sensor.windy_pm_2_5
                    name: Particulate Matter
          - type: entities
            entities:
              - input_boolean.mode_guest_mode
          - type: entities
            entities:
              - switch.byss
          - break
          # - type: entities
          #   title: Entryway
          #   show_header_toggle: false
          #   entities:
          - type: custom:simple-thermostat
            entity: climate.netatmo_living_room
            name: Livingroom
            icon: false
            control: false
            sensors:
              - entity: climate.netatmo_living_room
                attribute: preset_mode
                name: Mode
            style: |
              ha-card {
                --st-font-size-xl: 30px;
                --st-font-size-m: 20px;
                --st-font-size-sensors: 14px;
                --st-spacing: 2px;
              }
          - type: horizontal-stack
            cards:
              - type: entities
                show_header_toggle: false
                entities:
                  - entity: light.livingroom_ceiling_lights
                    name: Ceiling
                  - entity: light.livingroom_floor_lamp
                    name: Floor Lamp
                  - entity: light.livingroom_accent_lights
                    name: Accent
                  - entity: light.ikea_of_sweden_tradfri_bulb_e14_cws_opal_600lm_d90f45fe_1
                    name: Star of Bethlehem
                    icon: mdi:star
                  - type: divider
                  - entity: scene.livingroom_work
                    icon: mdi:briefcase-outline
                    name: Work
                  - entity: scene.livingroom_night_light
                    icon: mdi:weather-night
                    name: Night Light
                  - entity: scene.livingroom_off
                    icon: mdi:circle-off-outline
                    name: 'Off'
                footer:
                  type: buttons
                  entities:
                    - entity: scene.livingroom_off
                      icon: mdi:circle-off-outline
                      tap_action:
                        action: call-service
                        service: scene.turn_on
                        service_data:
                          entity_id: scene.livingroom_off
                    - entity: scene.livingroom_night_light
                      icon: mdi:weather-night
                      tap_action:
                        action: call-service
                        service: scene.turn_on
                        service_data:
                          entity_id: scene.livingroom_night_light
              - type: vertical-stack
                cards:
                  - type: custom:mini-graph-card
                    name: Temperature
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    lower_bound: 15
                    line_color: '#FFC107'
                    entities:
                      - sensor.airco2ntrol_temperature
                  - type: custom:mini-graph-card
                    name: Carbon Dioxide
                    entities:
                      - sensor.airco2ntrol_carbon_dioxide
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    line_color: '#DEBAFC'
                    # colors from https://material.io/design/color/#color-theme-creation
          - type: custom:simple-thermostat
            entity: climate.netatmo_bedroom
            name: Bedroom
            icon: false
            control: false
            sensors:
              - entity: climate.netatmo_bedroom
                attribute: preset_mode
                name: Mode
            style: |
              ha-card {
                --st-font-size-xl: 30px;
                --st-font-size-m: 20px;
                --st-font-size-sensors: 14px;
                --st-spacing: 2px;
              }
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: light.ikea_tradfri_bulb_e27_opal_1000lm_1
                    name: Ceiling
                  # - entity: light.yavin_strip
                  #   icon: mdi:led-strip-variant
                  #   name: Bed     
                  - type: divider
                  - entity: scene.bedroom_off
                    icon: mdi:circle-off-outline
                    name: 'Off'
              - type: vertical-stack
                cards:
                  - type: custom:mini-graph-card
                    name: Temperature
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    lower_bound: 12
                    line_color: '#FFC107'
                    entities:
                      - entity: sensor.sleepy_temperature
                        name: Temperature
                  - type: custom:mini-graph-card
                    name: Humidity
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    line_color: '#03A9F4'
                    entities:
                      - entity: sensor.sleepy_humidity
                        name: Humidity
          - break
          - type: media-control
            entity: media_player.spotify
          - type: media-control
            entity: media_player.living_room
          - type: entities
            title: Wake-up Lights
            show_header_toggle: false
            entities:
              - input_datetime.wakeup_time
              - entity: automation.wake_me_up_using_bedroom_lights
                name: "Wake-up lights"
                icon: mdi:theme-light-dark
              - input_boolean.wakeup_weekend

  - title: Floor plan
    path: floorplan
    icon: mdi:floor-plan
    # icon: mdi:map
    panel: true
    # id: system
    cards:
      - type: 'custom:floorplan-card'
        # show_header_toggle: false
        config:
          image: /local/floorplan.svg
          stylesheet: /local/floorplan.css
          rules:
            - entities:
                - binary_sensor.sleepy_status
              # state_transitions:
              #   - duration: 5
              #     from_state: 'on'
              #     to_state: 'off'
              states:
                - class: 'binary-sensor-off'
                  state: 'off'
                - class: 'binary-sensor-on'
                  state: 'on'
            # - entity: light.ikea_tradfri_bulb_e27_opal_1000lm_1
              # states:
              #   - state: 'on'
              #     class: 'bedroom-overlay'
              #   - state: 'off'
              #     class: 'bedroom-overlay'
              # action:
              #   domain: light
              #   service: toggle
            # - entity: binary_sensor.lumi_lumi_sensor_magnet_0e017b02_on_off
            #   states:
            #     - state: Closed
            #       class: entrance-closed
            - entity: light.tv
              states:
                - class: 'binary-sensor-off'
                  state: 'off'
                - class: 'binary-sensor-on'
                  state: 'on'
            - entity: binary_sensor.lumi_lumi_sensor_magnet_0e017b02_on_off
              states:
                - class: 'door-open'
                  state: 'on'
                - class: 'door-closed'
                  state: 'off'

  - title: Plants
    path: plants
    icon: mdi:leaf
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_columns: 3
        cards:
          - type: custom:daytime-card
            entity: sun.sun
          - type: weather-forecast
            entity: weather.dark_sky
          - break
          - type: custom:flower-card
            entity: plant.ficus
          - type: custom:flower-card
            entity: plant.sansevieria_cylindrica_boncel
          - type: custom:flower-card
            entity: plant.callisia_repens
          - type: custom:flower-card
            entity: plant.basil
