# https://www.home-assistant.io/lovelace/
title: Home
resources:
  # https://momentjs.com/
  - url: /local/moment.js?v=2.24.0
    type: js
  # https://github.com/maykar/custom-header
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  # https://github.com/thomasloven/lovelace-card-mod
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  # https://github.com/thomasloven/lovelace-layout-card
    url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  # https://github.com/thomasloven/lovelace-fold-entity-row
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  # https://github.com/nervetattoo/simple-thermostat
  - url: /hacsfiles/simple-thermostat/simple-thermostat.js
    type: module
  # https://github.com/kalkih/mini-graph-card
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /local/clock-card.js?v=0.0.8
    type: js
  - url: /local/daytime-card/daytime-card.js?v=0.0.217
    type: js
custom_header:
  compact_mode: true
  conditional_styles:
    - entity: group.all_plants
      condition:                     
        state: problem
      tab:
        2:
          color: rgb(244, 179, 170)
background: var(--background-image)
views:

  - title: Overview
    path: overview
    icon: mdi:one-up
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_columns: 3
        cards:
          - type: custom:clock-card
            entity: person.jan
          - type: custom:daytime-card
            entity: sun.sun
          - type: weather-forecast
            entity: weather.dark_sky
          - type: entities
            entities:
              - input_boolean.mode_guest_mode
          - type: entities
            entities:
              - switch.byss
          - break
          - type: entities
            title: Entryway
            show_header_toggle: false
            entities:
              - entity: switch.wall_switch_158d000161469d
                name: Ceiling
          - type: custom:simple-thermostat
            entity: climate.netatmo_living_room
            name: Livingroom
            icon: false
            control: false
            sensors:
              - entity: climate.netatmo_living_room
                attribute: preset_mode
                name: Mode
            style: |
              ha-card {
                --st-font-size-xl: 30px;
                --st-font-size-m: 20px;
                --st-font-size-sensors: 14px;
                --st-spacing: 2px;
              }
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - type: custom:fold-entity-row
                    entity: light.livingroom_ceiling_lights
                    head:
                      entity: light.livingroom_ceiling_lights
                      name: Ceiling
                    entities:
                      - light.ikea_tradfri_bulb_gu10_ws_400lm_1
                      - light.ikea_tradfri_bulb_gu10_ws_400lm_2
                      - light.ikea_tradfri_bulb_gu10_ws_400lm_3
                      - light.ikea_tradfri_bulb_gu10_ws_400lm_4
                  - entity: switch.osram_plug_1
                    name: Floor Lamp
                    icon: mdi:floor-lamp
                  - entity: light.livingroom_accent_lights
                    name: Accent
                  - light.tv
                  - light.shelf
                  - type: divider
                  - entity: scene.livingroom_night_light
                    icon: mdi:weather-night
                    name: Night Light
                  - entity: scene.livingroom_off
                    icon: mdi:circle-off-outline
                    name: 'Off'
              - type: vertical-stack
                cards:
                  - type: custom:mini-graph-card
                    name: Temperature
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    lower_bound: 15
                    line_color: '#FFC107'
                    entities:
                      - sensor.airco2ntrol_temperature
                  - type: custom:mini-graph-card
                    name: Carbon Dioxide
                    entities:
                      - sensor.airco2ntrol_carbon_dioxide
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    line_color: '#DEBAFC'
                    # colors from https://material.io/design/color/#color-theme-creation
          - type: custom:simple-thermostat
            entity: climate.netatmo_bedroom
            name: Bedroom
            icon: false
            control: false
            sensors:
              - entity: climate.netatmo_bedroom
                attribute: preset_mode
                name: Mode
            style: |
              ha-card {
                --st-font-size-xl: 30px;
                --st-font-size-m: 20px;
                --st-font-size-sensors: 14px;
                --st-spacing: 2px;
              }
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: light.ikea_tradfri_bulb_e27_opal_1000lm_1
                    name: Ceiling
                  # - entity: light.yavin_strip
                  #   icon: mdi:led-strip-variant
                  #   name: Bed
                  - entity: light.gateway_light_7811dcfaea5b
                    name: Gateway         
                  - type: divider
                  - entity: scene.bedroom_off
                    icon: mdi:circle-off-outline
                    name: 'Off'
              - type: vertical-stack
                cards:
                  - type: custom:mini-graph-card
                    name: Temperature
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    lower_bound: 12
                    line_color: '#FFC107'
                    entities:
                      - entity: sensor.sleepy_temperature
                        name: Temperature
                  - type: custom:mini-graph-card
                    name: Humidity
                    hours_to_show: 6
                    points_per_hour: 4
                    hour24: true
                    line_color: '#03A9F4'
                    entities:
                      - entity: sensor.sleepy_humidity
                        name: Humidity
          - break
          - type: media-control
            entity: media_player.spotify
          - type: media-control
            entity: media_player.living_room
          - type: entities
            title: Wake-up Lights
            show_header_toggle: false
            entities:
              - input_datetime.wakeup_time
              - entity: automation.wake_me_up_using_bedroom_lights
                name: "Wake-up lights"
                icon: mdi:theme-light-dark
              - input_boolean.wakeup_weekend

  - title: Floor plan
    path: floorplan
    icon: mdi:map
    panel: true
    cards:
      - type: custom:layout-card
        layout: horizontal
        max_width:
          - 27%
          - 73%
        cards:
          - type: picture-elements
            image: /local/floorplan.png
            elements:
              - type: state-icon
                tap_action:
                  action: toggle
                entity: light.shelf
                style:
                  top: 47%
                  left: 42%
              - type: state-icon
                tap_action:
                  action: toggle
                entity: light.gateway_light_7811dcfaea5b
                style:
                  top: 50%
                  left: 4%

  - title: Plants
    path: plants
    icon: mdi:leaf
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_columns: 3
        cards:
          - type: custom:daytime-card
            entity: sun.sun
          - type: weather-forecast
            entity: weather.dark_sky
          - break
          - type: plant-status
            entity: plant.snowflower
          - type: plant-status
            entity: plant.balcony

  # - title: Test
  #   path: test
  #   icon: mdi:test-tube
  #   cards:
