- name: Office
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 70
  icon: mdi:briefcase

- name: Hafven
  latitude: !secret hafven_latitude
  longitude: !secret hafven_longitude
  radius: 70
  icon: mdi:clipboard-account
