esphome:
  name: windy
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Alderaan Legacy"
  password: !secret alderaan

logger:
  baud_rate: 0  # Disable logging via UART

api:
  password: !secret windy

ota:
  password: !secret windy

## Interface for the temperature+humidity sensor
## https://esphome.io/components/i2c.html
i2c:
  sda: GPIO23
  scl: GPIO22

## Interface for the particulate matter sensor
## https://esphome.io/custom/uart.html
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

sensor:
  - platform: uptime
    name: Windy Uptime Sensor
    id: windy_uptime
    
  - platform: wifi_signal
    name: Windy WiFi Signal Sensor
    id: windy_wifi_signal
  
  ## SHT31 temperature+humidity sensor
  ## https://esphome.io/components/sensor/sht3xd.html
  - platform: sht3xd
    temperature:
      name: Windy Temperature
      id: windy_temperature
    humidity:
      name: Windy Humidity
      id: windy_humidity

  ## SDS011 particulate matter sensor
  ## https://esphome.io/components/sensor/sds011.html
  - platform: sds011
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
      id: windy_particulate_matter_2_5
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
      id: windy_particulate_matter_10_0
    update_interval: 5min

binary_sensor:
  - platform: status
    id: windy_status
    name: Windy Status
