esphome:
  name: sleepy
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: Alderaan Legacy
  password: !secret alderaan

logger:

api:
  password: !secret sleepy

ota:
  password: !secret sleepy

sensor:
  - platform: uptime
    name: Sleepy Uptime

  - platform: wifi_signal
    name: Sleepy WiFi Signal

binary_sensor:
  - platform: status
    name: Sleepy Status

  ## Motion sensor
  ## https://esphome.io/components/binary_sensor/gpio.html
  - platform: gpio
    name: Sleepy Motion Left
    id: sleepy_motion_left
    pin: GPIO12
    device_class: motion

text_sensor:
  - platform: version
    name: Sleepy ESPHome Version

light:
  ## Bed floor lighting
  ## https://esphome.io/components/light/neopixelbus.html
  - platform: neopixelbus
    name: Sleepy Strip
    id: strip
    type: GRBW
    pin: GPIO23
    variant: SK6812
    num_leds: 160
    effects:
      - random:
      - addressable_scan:
      - addressable_scan:
          name: Scan Long
          move_interval: 12ms
          scan_width: 8
      - addressable_twinkle:
      - addressable_random_twinkle:
          name: Random Twinkle Effect Slow
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_random_twinkle:
      - addressable_fireworks:

  ## Split floor lighting into partitions
  ## https://esphome.io/components/light/partition.html
  # - platform: partition
  #   name: Sleepy Right Partition
  #   segments:
  #     - id: strip
  #       from: 0
  #       to: 20

switch:
  - platform: shutdown
    name: Sleepy Shutdown
